### ISSUE TITLE
Ref:Can I have only integer values in Y - axis when actual values may be non-integer? #1047

### ISSUE THREAD

**Issue by DinooliUduwarage** [apexcharts/apexcharts.js#1056] opened 2019-11-06 05:00 UTC
**I'm Re opening my issues since the option you have provided is not solving my issue**
Reference:[ https://github.com/apexcharts/apexcharts.js/issues/1047]
In here you can get integer values to the y axis but, if the bar graph actual value is also rounded up or down to nearest integer. When you hover over the bar you see 36 if the actual value is 35.7, and 42 when actual value is 42,3.
![12](https://user-images.githubusercontent.com/36589723/68174949-a1c15700-ffa5-11e9-8f04-d6ed91f7196f.png)
This is my actual value 35.5, but here the y axis values have decimal points,where I have limited to 2 points.
![11](https://user-images.githubusercontent.com/36589723/68174916-87877900-ffa5-11e9-90ad-029fce8bef8b.png)
This is how u get values when applied above function, you can see there my actual value is rounded up n y axis have integers
**what I need is to display my actual value as it is in decimal points and y axis have only integer values**
@junedchhipa

**Comment by junedchhipa** [comment] 2019-11-08 13:59
You mean show integer values in y-axis and float values in the tooltip?
You can do this

```javascript
yaxis: {
    labels: {
        formatter: function(val) {
            return val.toFixed(0)
        }
    }
},
tooltip: {
    y: {
        formatter: function(val) {
            return val
        }
    }
}
```

**Comment by junedchhipa** [comment] 2019-11-08 14:00
Duplicate of #1047

**Closed by junedchhipa** 2019-11-08 13:59 UTC
