### ISSUE TITLE
IE-11 - Download SVG/PNG options doesn't work.

### ISSUE THREAD

**Issue by irshadahmed** [apexcharts/apexcharts.js#523] opened 2019-04-19 06:21 UTC
## Explanation

- What is the behavior you expect?
     Clicking on download SVG / PNG should download the image.
- What is happening instead?
    Nothing happens when you click on Download SVG / Download PNG option in IE-11
- What error message are you getting?
    There is no script error.

Note: You can load any of the demo graph in IE and reproduce the issue.

FYR:
![image](https://user-images.githubusercontent.com/8254178/56410116-96bd0880-6299-11e9-9f44-c58a3fcd9d0e.png)

**Comment by adpeyre** [comment] 2019-04-19 06:58
With Edge, same issue.

https://github.com/apexcharts/apexcharts.js/issues/518

**Comment by junedchhipa** [comment] 2019-04-19 18:14
Closing as duplicate of #518 
Will take a look soon.

**Closed by junedchhipa** 2019-04-19 18:14 UTC
