### ISSUE TITLE
When every data in series has only 1 value, all series data are bound to the first category value of xaxis(Why was this closed & falsely dismissed as repeatative data?)

### ISSUE THREAD

**Issue by dev-debug** [apexcharts/apexcharts.js#1183] opened 2020-01-03 20:03 UTC
I don't know why this issue was closed? Can someone please explain why this issue was closed without proper answer? I'm rewriting the problem. 

This [answer given here](https://github.com/apexcharts/apexcharts.js/issues/1182#issuecomment-570670997) does't solve the problem nor answer the scenario i am asking about

And Column distributed chart doesn't solve the problem either for my case where I've a 3 dimensions of data 1) data -total_margin 2)ProductCategory 3)Year
And my data isn't repetitive as was dismissed by the answer given above. 

I have a series like this

> series: [{
name: 'Bikes',
data: [16240314.115]
}, {
name: 'Bikes',
data: [9520869.049]
}, {
name: 'Bikes',
data: [27832356.658]
}, {
name: 'Bikes',
data: [532399.178]
}, {
name: 'Clothing',
data: [1598657.794]
}, {
name: 'Clothing',
data: [135523.664]
}, {
name: 'Accessories',
data: [4347678.462]
}, {
name: 'Accessories',
data: [376470.596]
}],

And And categories for xaxis as

> xaxis: {
categories: ['2011', '2012', '2013', '2014',' 2013', '2014', '2013', '2014'],
}

**_where every(name,data) pair in the series corresponds to a year in categories correspondingly, so 3 pairs of (Bike,data) corresponds to 3 different year._**

**_And Distributed Columns doesn't provide me the provision to include "Year"_**

**_Like I said I need to show -Year,ProductCategory and Total_Margin in the chart_**

I have a column apex chart. When every series data has 1 value, the chart are bound to the first categories value of xaxis.

I have a column apex chart. When every series data has 1 value, the chart are bound to the first categories value of xaxis.

Then every series data are bound to 2011 in the chart(and not to any other years in the categories)

This scenario happens with every kind of apex chart available on your website

I've the data in this format only, how do i create an apex chart(any apex chart) with the present data

And how do i define the data gap of Y-axis(my data are hugh and I want to give some custom smaller gap format for Y-axis)?

The entire code is below including codepen

`var options = {
series: [{
name: 'Bikes',
data: [16240314.115]
}, {
name: 'Bikes',
data: [9520869.049]
}, {
name: 'Bikes',
data: [27832356.658]
}, {
name: 'Bikes',
data: [532399.178]
}, {
name: 'Clothing',
data: [1598657.794]
}, {
name: 'Clothing',
data: [135523.664]
}, {
name: 'Accessories',
data: [4347678.462]
}, {
name: 'Accessories',
data: [376470.596]
}],

    chart: {
      type: 'bar',
      height: 650,
      width:900
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '55%',
        endingShape: 'rounded'
      },
    },
    dataLabels: {
      enabled: false
    },
    stroke: {
      show: true,
      width: 2,
      colors: ['transparent']
    },
    xaxis: {
      categories: ['2011', '2012', '2013', '2014',' 2013', '2014', '2013', '2014'],
    },
    yaxis: {
      title: {
        text: '$ (thousands)'
      }
    },
    fill: {
      opacity: 1
    },
    tooltip: {
      y: {
        formatter: function (val) {
          return "$ " + val + " thousands"
        }
      }
    }
  };

  var chart = new ApexCharts(document.querySelector("#chart"), options);
  chart.render();
`
[CodePen Issue](https://codepen.io/dev-debug/pen/ExabEbG)

**Comment by sergkop** [comment] 2020-01-04 01:14
For starters, try to be nice. Your issue is not a bug report. You are asking for help, but it sound as if you are demanding an answer. This is an open source project and no one gets paid to deal with this or a thousand other issues.

> I've the data in this format only, how do i create an apex chart(any apex chart) with the present data

Software libraries don't work by trying to fit the data format you have. They expect you to pass the data in a specific format. For apexcharts the data must be passed in the format [according to documentation](https://apexcharts.com/docs/series/). Your data needs to be transformed, which requires basic JS knowledge and is beyond the scope of this discussion.

You wrongly assumed that each item is `series` array corresponds to an x-axis category is the same order. That's not how it works.

What you probably wanted to achieve is in [this codepen](https://codepen.io/sergkop/pen/GRgOXZE).
```
xaxis: {
    categories: ['2011', '2012', '2013', '2014']
},
```
and
```
series: [{
    name: 'Bikes',
    data: [16240314.115, 9520869.049, 27832356.658, 532399.178]
}, {
    name: 'Clothing',
    data: [NaN, NaN, 1598657.794, 135523.664]
}, {
    name: 'Accessories',
    data: [NaN, NaN, 4347678.462, 376470.596], 
}],
```

Hopefully, that will help you to move forward. I don't have that much time to dig into the rest of your requirements.

**Comment by junedchhipa** [comment] 2020-01-04 19:46
The code provided by @sergkop is in a valid format. Please adjust your series data this way and you will be able to render the chart correctly.
Closing this as it is not a bug in ApexCharts.

**Closed by junedchhipa** 2020-01-04 19:46 UTC
Labels: support

**Comment by dev-debug** [comment] 2020-01-06 17:32
Hey @sergkop ,

For starter, apex chart has premium service (even if its open source). Since, I asked here politely in the first post,my question was dismissed as repeatative data & tagged "closed" within a few minutes I posted. Yes, I don't expect much from community service without availing premium service of apex charts. But its rude & arrogant to just close it immediately without a chance for other people to view it. I'm new to web development. And yes, I appreciate your short answer but please try to understand why I was upset to be dismissed & closed without a chance & clarity. I wasn't demanding my answer. I was asking why my first question was closed. If the answer was easy basic javascript, then people who closed my answered my question missed out basic javascript option on their product for a most common scenario
https://apexcharts.com/plans/
