### ISSUE TITLE
Stacked and single/grouped column in combination

### ISSUE THREAD

**Issue by sanketkarandikar** [apexcharts/apexcharts.js#854] opened 2019-08-21 06:46 UTC
Hello @junedchhipa, i struggled a lot to get this but at the time i just cant find any proper solution. I want to create a chart where 1 column is stacked with 2 dataSeries and 1 column is seperate. I have created a fiddle where i am showing three separate columns. Instead what i would like to do is stack first 2 data series and keep 3rd in separate column.
Codepen for the same - [https://codepen.io/sanket-karandikar/pen/OKaZYE](url)
Now how can i stack green and orange bar together and keep red separate?

TIA

**Comment by junedchhipa** [comment] 2019-09-06 10:38
This feature is not available yet but may come in future.

**Comment by junedchhipa** [comment] 2020-01-05 14:56
Closing as duplicate of #196

**Closed by junedchhipa** 2020-01-05 14:56 UTC
Labels: feature-request
