### ISSUE TITLE
Categories disappear when we shift from a time series to a categories chart

### ISSUE THREAD

**Issue by divye11** [apexcharts/apexcharts.js#744] opened 2019-07-06 09:02 UTC
## Explanation

- What is the behavior you expect?
I am using redux to update the values provided to chart in React JS web panel. The problem is when I shift from time series to category the categories on x-axis disappear.

This is my code.
Component.js

```<Chart options={this.props.options} series={this.props.series} type="area" height="387" />```
 
In the reducer, I change my data like this,

```case RECEIVE_UNIQUE_VISITORS:
      console.log(action.categories); //categories in chart
      console.log(action.chartData); //series component in chart
      return { ...state,
        unique_visitors: action.payload,
        loading_unique_visitors: false,
        chartData: action.chartData,
        timeData: action.timeData,
        categories: action.categories,
        options: {
          ...state.options,
          xaxis: {
            ...state.options.xaxis,
            categories: action.categories,
            type: _.isEmpty(action.categories) ?  'datetime' : '',
          }
        },
        series: [{ name: 'unique visitors', data: action.chartData }]
      };
```

I logged the series object and categories object sent to Chart component, the chart is supposed to update according to the period selected, monthly, weekly, so on. 

![Screenshot 2019-07-06 at 2 17 52 PM](https://user-images.githubusercontent.com/30335469/60754111-15eced80-9ffa-11e9-8b60-fe97244835da.png)
Categories object is empty and the latter is series object data.
![Screenshot 2019-07-06 at 2 21 44 PM](https://user-images.githubusercontent.com/30335469/60754112-18e7de00-9ffa-11e9-879d-8d4241d84083.png)
This shows the graph.

![Screenshot 2019-07-06 at 2 16 08 PM](https://user-images.githubusercontent.com/30335469/60754142-66644b00-9ffa-11e9-9e2d-4652e64350c1.png)
This shows the logged categories object and series object
![Screenshot 2019-07-06 at 2 16 31 PM](https://user-images.githubusercontent.com/30335469/60754147-8267ec80-9ffa-11e9-9232-51fed4d291cd.png)
Here the x-axis elements(categories) won't show. When done statically I can see the x-axis elements.

This
- What is happening instead?

X-axis elements won't show in the graph when given as categories.

**Comment by junedchhipa** [comment] 2020-01-23 15:50
Closing it as cannot reproduce it in v3.15.2
If you can post a working codepen / codesandbox demo, I will re-open the issue.

**Closed by junedchhipa** 2020-01-23 15:50 UTC
