### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by ChrisFisch** [apexcharts/apexcharts.js#1228] opened 2020-01-17 10:59 UTC
When I'm zooming into my Chart and press the homebutton afterwards, it zooms into the wrong size.

![image](https://user-images.githubusercontent.com/59999944/72607264-98972380-3920-11ea-983d-76e2420d7517.png)
now if I press the button:

![image](https://user-images.githubusercontent.com/59999944/72607329-b6fd1f00-3920-11ea-9b6b-314f1fdaa818.png)

Thanks in advance :D, Chris

**Comment by junedchhipa** [comment] 2020-01-17 11:01
Which version you're using?
Can I see a [codepen](https://codepen.io/apexcharts/pen/xYqyYm) example, please?

**Comment by ChrisFisch** [comment] 2020-01-17 11:14
Hey! Thanks for your fast reply.
To be honest, I don't know which version I'm using, I integrate it with this HTML line:
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

I'm using some kind of this one: https://codepen.io/apexcharts/pen/QrbEQg

**Comment by junedchhipa** [comment] 2020-01-17 11:16
If you're using the link, you're using the latest version.

Unfortunately, I cannot reproduce the issue.

**Comment by junedchhipa** [comment] 2020-01-20 18:27
Closing as not reproducible.

**Closed by junedchhipa** 2020-01-20 18:27 UTC
Labels: can't reproduce
