### ISSUE TITLE
There is a way to auto generate trend line in scatter chart?

### ISSUE THREAD

**Issue by LaurenceM10** [apexcharts/apexcharts.js#1248] opened 2020-01-24 21:48 UTC
Hi guys, there is a way to auto generate trend line in scatter chart?

In this chart: https://apexcharts.com/vue-chart-demos/mixed-charts/line-scatter/

**Comment by junedchhipa** [comment] 2020-01-28 18:05
Sorry, currently there is no way to generate trendline automatically.
Closing as duplicate of #413

**Closed by junedchhipa** 2020-01-28 18:05 UTC
