### ISSUE TITLE
Selection inconsistent 

### ISSUE THREAD

**Issue by MACscr** [apexcharts/apexcharts.js#463] opened 2019-04-01 20:30 UTC
## Codepen

https://codepen.io/MACscr/pen/yrBjKP

## Explanation

When trying to select the last 5% or so of the chart to the right, nothing happens. It doesnt zoom as expected. Sometimes when moving the selection to the end, it even disappears. Im not seeing any console errors, but typically when this issue happens, i have to refresh the page for it to even start working again on the rest of the chart. I can attach a video showing the issue if that helps.

**Comment by junedchhipa** [comment] 2019-05-29 10:01
Closing as duplicate of #578

**Closed by junedchhipa** 2019-05-29 10:01 UTC
