### ISSUE TITLE
Stroke colors on area chart don't change

### ISSUE THREAD

**Issue by razorext2** [apexcharts/apexcharts.js#4703] opened 2024-09-14 06:40 UTC
### Description
Cant change the stroke color. 
i've following the documentation about how can we config the stroke elements, but when i started to change the color, the stroke disappear

### Steps to Reproduce

1. Using area chart
2. change the blue color of the stroke to whatever colors

### Reproduction Link

here is the [sanbox](https://codepen.io/razorext/pen/PorvYjP)

**Comment by SimonMayer** [comment] 2024-09-14 09:02
According to the [docs](https://apexcharts.com/docs/options/stroke/), colors should be provided as an array
```
  stroke: {
    width: 3,
    colors: ["#00ff00"]
  },
```

**Comment by brianlagunas** [comment] 2024-09-16 14:27
Thanks @SimonMayer for answering this issue. Closing as not a bug.

**Closed by brianlagunas** 2024-09-16 14:27 UTC
Labels: bug
