### ISSUE TITLE
ApexCharts access dataURI without rendering chart to user screen

### ISSUE THREAD

**Issue by careignition-cps** [apexcharts/apexcharts.js#2819] opened 2021-12-09 19:06 UTC
### Description

Attempting to use ApexCharts to create a chart only for the sake of accessing the URI in order to save it to a pdf. 

All I want is the URI. Can I get that without rendering the image?

### Steps to Reproduce

```
function uriFunction() {
  const options = {
    series: [
      {
        name: 'Desktops',
        data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
      }
    ],
    chart: {
      height: 350,
      type: 'line',
      zoom: {
        enabled: false
      }
    },
    dataLabels: {
      enabled: false
    },
    stroke: {
      curve: 'straight'
    },
    title: {
      text: 'Product Trends by Month',
      align: 'left'
    },
    grid: {
      row: {
        colors: ['#f3f3f3', 'transparent'], // takes an array which will be repeated on columns
        opacity: 0.5
      }
    },
    xaxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep']
    }
  };
  const d = document.createElement('div');
  d.setAttribute('id', 'example');
  const example = new ApexCharts(document.querySelector('#example'), options);
  example.render();
  console.log('in func');
  console.log(example.dataURI());
  return example.dataURI();
}

```

Console.log(uriFunction()) returns an uncaught promise error.

### Expected Behavior
Console.log(uriFunction()) should return the URI (the string).
### Actual Behavior
Console.log(uriFunction()) returns an error of an uncaught promise.
### Reproduction Link
https://codepen.io/cstebbins/pen/jOGrRwZ?editors=1011

**Comment by junedchhipa** [comment] 2021-12-18 15:15
`dataUri` needs the chart to be rendered first. It cannot be called directly.
Closing as this is not a bug, but intended behavior.

**Closed by junedchhipa** 2021-12-18 15:15 UTC
