### ISSUE TITLE
Y-axis put image ?

### ISSUE THREAD

**Issue by JACK123wang** [apexcharts/apexcharts.js#557] opened 2019-04-29 09:13 UTC
HI!
I want to put icon to y-axis ,but I don't find any method to do it.

example:
![擷取3](https://user-images.githubusercontent.com/47593069/56886555-d8bc2a80-6aa1-11e9-8b10-f12cf37fa003.PNG)
Put the icon of sun to Y-axis.
thank you for your help!

**Comment by junedchhipa** [comment] 2019-05-04 06:58
Duplicate of #574

**Closed by junedchhipa** 2019-05-04 06:58 UTC
