### ISSUE TITLE
Click on first legend causes tooltip x value NaN undefined.

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#829] opened 2019-08-06 11:05 UTC
In my multiline chart series(xaxis type is datetime and date is same for all three series), if I click on the first legend to hide series this causes tooltip x value NaN undefined problem. But the other legend did not cause this type of problem. now using 3.8.4v. and the older version has the same problem. @junedchhipa 

this is my legend configuration:
```
legend: {
    show: true,
    position: 'top',
    showForNullSeries: false,
    showForZeroSeries: false,
},
```

made a gif for better understanding
![deepin-screen-recorder_Select area_20190806165727](https://user-images.githubusercontent.com/28239287/62535061-4da2bb80-b86c-11e9-95c6-d2cd0d25158e.gif)

**Comment by kaminilsen** [comment] 2019-08-08 23:16
You need to define your xaxis categories, see https://apexcharts.com/docs/options/xaxis/

**Comment by junedchhipa** [comment] 2019-08-25 09:53
@Sumon-miazi Please create a working codepen to reproduce easily.

**Comment by junedchhipa** [comment] 2020-01-16 15:20
Unable to reproduce it, hence closing it.

**Closed by junedchhipa** 2020-01-16 15:20 UTC

**Comment by lucasdcrk** [comment] 2020-05-09 10:05
Hi! @junedchhipa I encountered the same issue and recreated it on code sandbox 
See https://codesandbox.io/s/vue-basic-example-qejof?file=/src/components/Chart.component.vue
