### ISSUE TITLE
Performance issue when hiding series by click on legend for charts with large number of datapoints

### ISSUE THREAD

**Issue by Au6ojlut** [apexcharts/apexcharts.js#4534] opened 2024-06-19 15:45 UTC
### Steps to Reproduce

1.  Open https://apexcharts.com/features/ and scroll to High Performance section
2.  Choose 25000 points and click render 
![image](https://github.com/apexcharts/apexcharts.js/assets/3740927/fec21824-44d8-4766-99fd-2d0bae20dd49)

3.  Click on legend `series-1`
4.  Page stops responding
![image](https://github.com/apexcharts/apexcharts.js/assets/3740927/b822e480-e111-41b2-b5d5-1c19c2f89878)
![image](https://github.com/apexcharts/apexcharts.js/assets/3740927/646774aa-2ae8-4d26-8e11-beb45a9ab1f8)

----

Looks like setAttribute is called for each dot and it cost a lot.
firefox
![image](https://github.com/apexcharts/apexcharts.js/assets/3740927/f707ed43-e037-44ec-a77a-598d8dbc12d8)

chrome
![image](https://github.com/apexcharts/apexcharts.js/assets/3740927/c3315d78-a7ad-4828-aa3b-357dba28fd9a)

**Comment by rosco54** [comment] 2024-07-01 07:36
@junedchhipa I believe this is a duplicate of #4488, which was fixed by PR #4483. If so, it is fixed in release 3.49.2.

**Comment by junedchhipa** [comment] 2024-07-01 15:29
Yes, this is fixed and works as expected.

**Closed by junedchhipa** 2024-07-01 15:29 UTC
Labels: bug
