### ISSUE TITLE
Get an error "Cannot read property 'getPreviousPaths' of null" after the release

### ISSUE THREAD

**Issue by ryanle88** [apexcharts/apexcharts.js#626] opened 2019-05-28 03:57 UTC
I am using vue-apexcharts for a project and everything has been working fine until now.

However, with the recent release (v3.7), I got an error "Cannot read property 'getPreviousPaths' of null" for all the charts (bar chart and pie chart).

Please advice what I need to do to remove this error

![Screen Shot 2019-05-27 at 10 53 08 PM](https://user-images.githubusercontent.com/5439020/58450025-b8987f00-80d2-11e9-870a-b7c99c7bdcd2.png)

**Comment by junedchhipa** [comment] 2019-05-28 14:37
Please provide a codepen or codesandbox demo for me to reproduce.

**Comment by junedchhipa** [comment] 2019-05-28 17:05
Did you found the fix for the issue as you’ve closed it?

**Comment by ryanle88** [comment] 2019-05-28 17:43
Yes, it was my fault. The way I saved data to vuex caused the issue when I refreshed the page since all the data got wiped out. Thank you for your quick response!

**Comment by oddjobz** [comment] 2019-05-30 11:52
Interesting, I have this too .. tried all sorts of things to fix .. finally downgraded to 3.6.7 and it works fine again.

**Comment by wsabol** [comment] 2019-05-30 15:14
I'm getting the same error now using the direct script from cdn.jsdelivr.net/npm/apexcharts

![image](https://user-images.githubusercontent.com/12749601/58642863-c3663600-82c3-11e9-8cfd-e91b820b35c2.png)

**Comment by oddjobz** [comment] 2019-05-30 15:24
Mmm, I tried messing with my Vuex handling .. nothing seemed to make any difference, it looks like the way apexcharts initialises is no longer compatible with the vue- shim ..

**Comment by junedchhipa** [comment] 2019-05-30 17:02
Can anyone create a codesandbox demo with the simplest configuration so I can jump into it quickly?

**Comment by wsabol** [comment] 2019-05-30 17:26
this is my situation.
https://codepen.io/wsabol/pen/WBaBJj

looks like it because the chart is not visible. I need to updateOptions behind the scenes. But it errors out when the parent div is display:none

**Comment by junedchhipa** [comment] 2019-05-30 17:54
Thanks for the demo. It was a small conditional check I missed.

**Closed** 2019-05-30 17:55 UTC

**Comment by junedchhipa** [comment] 2019-06-01 12:59
Released 3.7.1
Let me know if it fixes the issue.

**Comment by oddjobz** [comment] 2019-06-02 19:47
Yeah, that looks to work, many thanks! :)

**Comment by wsabol** [comment] 2019-06-03 02:18
Yes works for me.
