### ISSUE TITLE
tickAmount doesn't work for x axis type: 'category'

### ISSUE THREAD

**Issue by joshleblanc** [apexcharts/apexcharts.js#939] opened 2019-09-26 16:20 UTC
## Codepen

https://codepen.io/ThirdSign/pen/pozBRrw

## Explanation

- What is the behavior you expect?
The tickAmount option should set the number of ticks

- What is happening instead?
It's not setting the number of ticks

- What error message are you getting?
There's no error message

**Comment by junedchhipa** [comment] 2019-09-26 18:18
As you have numerical values in the x-axis, you should change the `xaxis.type: numeric`
Once you do that, tickAmount will work.

**Comment by joshleblanc** [comment] 2019-09-26 20:31
Thansk for the quick response.

Updating the values to strings, the problem persists. I've updated the code pen.

**Comment by janvanhelvoort** [comment] 2019-10-02 06:10
@junedchhipa, the problem still persists. Could you look again?

**Comment by duckyb** [comment] 2020-03-10 10:43
Please add to the documentation that tick amount does not work if you are using xaxis categories.

**Comment by Grekus14** [comment] 2020-08-07 05:47
I'm encountering the same problem. However, I have irregular time data for the x-axis, meaning if I set it to numeric, the distance between data points becomes irregular (in some places it's grouped together and in others data points are very far apart). How do I make all the data points equal distance apart If I'm using numeric? Thanks!

**Comment by junedchhipa** [comment] 2020-08-31 18:00
Added support for tickAmount in category x-axis.
A new version 3.20.1 will be released soon with this enhancement.

**Closed** 2020-08-31 17:59 UTC
Labels: feature-request, xaxis

**Comment by sophiabarclay** [comment] 2020-10-09 15:15
> Added support for tickAmount in category x-axis.
> A new version **3.20.1** will be released soon with this enhancement.

Are there any updates on this?

**Comment by StarryFire** [comment] 2020-10-15 09:18
Hi, this is still not working. 
```
xaxis: {
      type: 'category',
      categories: [
        'Apr 30, 2020',
        'May 31, 2020',
        'Jun 30, 2020',
        'Jul 31, 2020',
        'Aug 31, 2020',
        'Sep 30, 2020',
      ],
      tickAmount: 2,
      title: {
        text: 'Days',
      },
    }
```

**Comment by fuoridallarete** [comment] 2021-02-11 10:25
> Hi, this is still not working.
> 
> ```
> chart: {
>      type: 'line',
> },
> xaxis: {
>       type: 'category',
>       categories: [
>         'Apr 30, 2020',
>         'May 31, 2020',
>         'Jun 30, 2020',
>         'Jul 31, 2020',
>         'Aug 31, 2020',
>         'Sep 30, 2020',
>       ],
>       tickAmount: 2,
>       title: {
>         text: 'Days',
>       },
> },
> series: {
>     data: [1, 2, 3, 4, 5, 6]
> }
> ```
> 
> This shows me `Apr 30, 2020` , `Jun 30, 2020` and `Aug 31, 2020` . This should should only 2 ticks not 3.

Have you sorted it somehow?

**Comment by mcristo1844** [comment] 2021-04-09 14:30
I also noticed an issue here where tickAmount does not work on bar charts(horizontal: true) when using a category array.  It does however work on column charts, although not to the exact amount as others have already indicated.

**Comment by imasubmarine** [comment] 2022-01-17 10:50
In fact tickAmount does work with bar charts(horizontal: true)  and a category array.
But since (horizontal:true) swap x and y, you have to set tickAmount for yaxis in xaxis, which is totally counter intuitive.
(because all other options still apply to the intended axis)
It took me some time to realize that.

I'm not sure if it's a bug or if it works as intended.

**Comment by cbutler90** [comment] 2022-03-21 19:43
This is also still an issue for me. I have tickAmount set to 2 and it's showing 1 sometimes and 2 other times. I'm using an area chart

**Comment by Amala4** [comment] 2023-11-16 21:11
Hello, has this issue been resolved. I am having the same problem

**Comment by maribeee** [comment] 2024-11-21 13:29
Also having this problem with line charts :( any updates? X-axis doesn't behave as expected when setting tickAmount to dataPoints or to specific number of ticks
