### ISSUE TITLE
When selecting datetime range, selection disappearing

### ISSUE THREAD

**Issue by vitalijm** [apexcharts/apexcharts.js#629] opened 2019-05-29 08:49 UTC
When user selecting by mouse range of two dates and selection goes out of chart, then selection immediately is disappearing.

I think something could be done with on mouse event 'mouseup'.

Highcharts js plugin don't have this problem, it keeps selection until user releasing mouse button and event 'mouseup' is fired.

Thanks.

**Comment by junedchhipa** [comment] 2019-05-29 10:02
Thanks for reporting.
The issue is already reported on #578 and will be fixed soon.
Closing as duplicate of #578

**Closed by junedchhipa** 2019-05-29 10:02 UTC
