### ISSUE TITLE
Treemap chart

### ISSUE THREAD

**Issue by renjiie** [apexcharts/apexcharts.js#862] opened 2019-08-22 06:21 UTC
I just want to know Apex has treemap charting for react js . If yes, is it supportive of drilling down to multilevels . 
Thanks

**Comment by junedchhipa** [comment] 2019-08-22 06:23
Sorry, treemap charts are currently not present in ApexCharts.
Duplicate of #646

**Closed by junedchhipa** 2019-08-22 06:23 UTC
