### ISSUE TITLE
Progressive increase chart size on resize window with height: "100%"

### ISSUE THREAD

**Issue by fakhamatia** [apexcharts/apexcharts.js#1609] opened 2020-05-15 09:01 UTC
# Progressive increase chart size on resize the window with `height: "100%"`

## Codepen
[https://codepen.io/fakhamatia/pen/VwvGGqz](https://codepen.io/fakhamatia/pen/VwvGGqz)

![Peek 2020-05-15 13-24](https://user-images.githubusercontent.com/20030910/82032294-3cff5b80-96b0-11ea-8d91-beaa9c0aee22.gif)

## Explanation

- What is the behavior you expect? Resize on and stop 
- What is happening instead? grow
- What error message are you getting? NO

**Comment by simplenotsimpler** [comment] 2020-05-15 18:55
Hi, this is a common issue with charts on Bootstrap cards, not just Apex Charts. To fix this, you need to set an explicit height on the containing CSS class. In this case, the Bootstrap card-body. Otherwise, it's 100% of the page. 

From https://github.com/apexcharts/apexcharts.js/issues/460#issuecomment-479172673:

> If you provide a "%" value in chart.height, the chart expects the parent element to have some fixed height. Otherwise, it goes into an infinite update. The infinite update happens because the chart listens on parent resize event, and updates again. As the update causes parent height to increase, it again fires the parent resize event, and so on.
> 
> So, if you provide '%' value in chart.height, please make sure, you have a fixed height parent.

Try something like this this to keep the height reasonably responsive:

`.card-body {
    height: 45vh;
}`

Google search: apex chart height keeps growing

HTH

**Comment by junedchhipa** [comment] 2020-05-16 09:50
Duplicate of #460

**Closed by junedchhipa** 2020-05-16 09:50 UTC

**Comment by fakhamatia** [comment] 2020-05-17 12:26
Sorry for not searching...
