### ISSUE TITLE
Column chart cuts off start and end.

### ISSUE THREAD

**Issue by CSondergaard** [apexcharts/apexcharts.js#1685] opened 2020-06-16 11:25 UTC
# Bug report
Columns get cut off at the start and end of the chart. This is using multi chart with 4 columns and 1 line.

## Codepen
https://codepen.io/CSondergaard/pen/VweKBQw

**Comment by liztra** [comment] 2020-06-23 09:04
I have the same problem with a similar chart

**Codepen:**
https://codepen.io/liztra/pen/rNxmyKr

**Comment by dmeigs** [comment] 2020-11-15 20:52
I had this problem as well. I discovered that if you change the chart type from "line" to "bar", it renders correctly. The example in the documentation shows the chart type as "line", but that seems to be incorrect.

**Comment by CSondergaard** [comment] 2020-12-07 13:18
> I had this problem as well. I discovered that if you change the chart type from "line" to "bar", it renders correctly. The example in the documentation shows the chart type as "line", but that seems to be incorrect.

This removes the data label background on the line.

**Comment by saulogiga** [comment] 2020-12-30 13:15
The correct resolution is to include the parameter stacked = false

chart: {
            fontFamily: 'Nunito, sans-serif',
            height: 350,
            type: 'line',
            stacked: false

**Comment by Carniatto** [comment] 2021-01-27 09:37
this was reported here also: https://github.com/apexcharts/apexcharts.js/issues/958#issuecomment-539441492

**Comment by alejandroeclair** [comment] 2021-02-18 00:24
This is still an ongoing issue in the latest release for react-apexcharts. Codepen: https://codepen.io/l1qu1d1c3/pen/eYBWWWW

**Comment by tomukasas** [comment] 2022-08-23 07:56
Seems like the issue is caused by grid mask. I was able to fix the issue by adding the following css:

`[id^=gridRectMask] {
  display: none;
}`

Please note that this is not a complete solution and you may need to tweak some other options for this to work nicely.

**Comment by jackwurth** [comment] 2022-12-05 01:49
I resolved this by calling `chart.zoomX(0)` which forces the whole chart to zoom out

**Comment by Nedpereira** [comment] 2023-02-28 22:19
Guys, I know that the problem is not the same, but I have a problem with two things. Whenever day 1 arrives my date is changing.. And when I try to use

forecastDataPoints: { count: 7 }

it appears in a few lines and then it gets erased

**Comment by DKirbi** [comment] 2023-05-11 11:19
I managed to fix the problem with specifying an array of categories in xaxis. By default the array is empty, but if you put in the exact label values of your xaxis, it gets magically fixed. So:
xaxis: {
categories: [1, 2, 3, 4, 5]
}
of course I am only playing around with mock data so it's a workaround. I've tried everything else and it did not work, all the other charts seem to work.

**Comment by VaidehiShrivastava** [comment] 2023-08-21 06:15
Tried everything but the chart isn't working correctly at the start and end.
<img width="1262" alt="Screenshot 2023-08-21 at 11 43 30 AM" src="https://github.com/apexcharts/apexcharts.js/assets/55225626/a698b5f5-34f1-4709-be5b-84717c3a6586">

**Comment by R1mmm** [comment] 2023-11-12 23:32
I have a same issue. And I also need to have tickPlacement as 'on' ... T . T  Is there anyone who can resolve this problem?
![image](https://github.com/apexcharts/apexcharts.js/assets/87795291/44a1a2ac-6885-45cb-8d60-d069a34294b6)

**Comment by junedchhipa** [comment] 2024-05-14 06:10
Does anyone still experiencing the issue?
As I checked with the latest version 3.49.1, this seems to be fixed.

In case this is still present, please provide a new Codepen as the original Codepen doesn't have this issue anymore. Closing this for now.

**Closed by junedchhipa** 2024-05-14 06:10 UTC
Labels: bug, bar

**Comment by homj** [comment] 2024-07-23 09:09
> Does anyone still experiencing the issue? As I checked with the latest version 3.49.1, this seems to be fixed.
> 
> In case this is still present, please provide a new Codepen as the original Codepen doesn't have this issue anymore. Closing this for now.

The issue still persists when setting a column width in pixels.
Possibly related: There's also a weird gap between the last two bars.
![Bildschirmfoto 2024-07-23 um 11 08 09](https://github.com/user-attachments/assets/3204c6df-e2d2-4b0c-a2fd-aac878214764)

Here's the codepen: https://codepen.io/homj/pen/OJeXvqy
