### ISSUE TITLE
Pie chart moved when series length is 1

### ISSUE THREAD

**Issue by duy-tran** [apexcharts/apexcharts.js#663] opened 2019-06-07 16:36 UTC
I have several pie chart align horizontally, legends at bottom. When a chart having series length of 1, it is moved to the top a few pixels. Check out this [example](https://codesandbox.io/s/vue-basic-example-47bk8).
![](https://i.ibb.co/5LfFG3g/apex.png)
By inspecting I found that `<g id="SvgjsG17745" class="apexcharts-inner apexcharts-graphical" transform="translate(0, -5)">...</g>` was transformed 5 px to the top in the example.

**Comment by junedchhipa** [comment] 2019-06-08 12:06
This is already fixed and will be released in 3.8.0 tomorrow.
Duplicate of #647

**Closed by junedchhipa** 2019-06-08 12:06 UTC
