### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' (apexcharts.min.js:6)

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [apexcharts/apexcharts.js#1952] opened 2020-10-03 00:55 UTC
Hello!
How can I improve to prevent the browser from showing such messages?

Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by simonmaass** [comment] 2020-11-18 10:23
+1 totally agree

**Comment by junedchhipa** [comment] 2020-11-20 17:57
Duplicate of #937

**Closed by junedchhipa** 2020-11-20 17:57 UTC
