### ISSUE TITLE
radialBar should support NON percentage value and also min max options

### ISSUE THREAD

**Issue by mburger81** [apexcharts/apexcharts.js#496] opened 2019-04-10 14:20 UTC
**Is your feature request related to a problem? Please describe.**
radialBar seems to work only with % which in most cases should work well. And we know we can calc % from our known max and min values.

We saw we can format the label by removing also the % symbol and at this point we can also calc from percentage to your value.

But isn't this a little bit tricky??
Would it not nice to have a min, max value and the % symbol should be added only with formatter and not as default? This behavior would be much more general purpose

Thx a lot

**Comment by junedchhipa** [comment] 2019-04-13 09:55
Good suggestion. Will think of it in future releases.
Closing it as it is a duplicate of #449

**Closed by junedchhipa** 2019-04-13 09:55 UTC
