### ISSUE TITLE
Shifted labels using 3.13.0

### ISSUE THREAD

**Issue by mtinnes** [apexcharts/apexcharts.js#1198] opened 2020-01-09 22:05 UTC
Upgrading to 3.13.0 has shifted y-axis labels up, crowding the title. Included screenshot:

![apexlabels](https://user-images.githubusercontent.com/6729389/72108682-c74a4400-32f9-11ea-8281-b56c1314febe.png)

**Comment by junedchhipa** [comment] 2020-01-10 06:08
Can you please provide a codepen demo? Or paste the options object so I can reproduce easily?

**Comment by junedchhipa** [comment] 2020-01-12 06:55
Closing as cannot reproduce.

**Closed by junedchhipa** 2020-01-12 06:55 UTC
Labels: yaxis
