### ISSUE TITLE
Top legend overlapping in line chart

### ISSUE THREAD

**Issue by valeLib** [apexcharts/apexcharts.js#310] opened 2019-02-04 19:42 UTC
When legend.position is set to top and there are many items provided the layout is overlapped.

![linechart](https://user-images.githubusercontent.com/24920877/52232341-0591e480-289b-11e9-9e34-8fb8abfa70ca.png)

I tried to setting a containerMargin on it but it doesn't work.

**Comment by junedchhipa** [comment] 2019-02-08 18:25
Can you please post your example as a codepen? Or post your configuration?
I tried adding many items in series and the legend is correctly placed above the chart area.
![screen shot 2019-02-08 at 11 53 22 pm](https://user-images.githubusercontent.com/17950663/52497741-e37ec600-2bfc-11e9-8c97-3251e2d35d22.png)

**Comment by junedchhipa** [comment] 2019-02-08 18:26
I suspect you're using an old version of ApexCharts
Maybe try apexcharts@3.2.2 which is the latest version?

**Comment by junedchhipa** [comment] 2019-02-14 19:35
Closing this as cannot reproduce it. Please provide a working codepen with the latest ApexCharts version.

**Comment by valeLib** [comment] 2019-03-14 19:25
Sorry I took so long to answer, I really appreciate the help provided.
Here is an example of the issue on [codesandbox](https://codesandbox.io/embed/z269jrlk5x?fontsize=14).

**Comment by yellowbang** [comment] 2020-03-28 00:41
Any update on this bug?
I have the some problem.  I am on version 3.17.0

**Comment by junedchhipa** [comment] 2020-03-28 08:15
@valeLib You had `legend.floating: true` which is causing the issue.
Please turn off `legend.floating` as this property takes the legend out of flow.

**Closed** 2020-03-28 08:16 UTC

**Comment by devesh-anand** [comment] 2022-06-24 12:12
So I went throught the documentation on apexcharts docs, and my `legend.floating` is set to `false`.
The issue, as you say, is fixed, but not completely since the legend overlaps when the chart is hovered. Maybe something to do with `tooltipHoverFormatter`?
