### ISSUE TITLE
x-axis values not rendered properly for real-time chart

### ISSUE THREAD

**Issue by ZORfree** [apexcharts/apexcharts.js#804] opened 2019-07-27 08:43 UTC
## Explanation

- What is the behavior you expect?
I would expect that in the x axis the sampling time of each values is rendered with the format ('HH:mm:ss')

- What is happening instead?
No data on x-axis
- What error message are you getting?
I don't get any error, the application does not crash and the graph looks fine, only the x-axis is incorrect.

sorry, I don't have Codepen account.   [http://playcode.io/384153](http://playcode.io/384153)

**Comment by morkeleb** [comment] 2019-11-11 09:21
Duplicate of #709 ?

**Comment by ZORfree** [comment] 2019-11-13 01:31
> Duplicate of #709 ?

There are some differences，His X-axis is not formatted correctly；My X-axis doesn't show the data

**Comment by junedchhipa** [comment] 2020-01-16 15:46
It seems the difference between each data point is in seconds/minutes and that's why ApexCharts is unable to handle the tiny timescale.
In such a case, I suggest using `xaxis.type: 'category'` and using a tiny datetime library (dayjs) to format will work.

**Closed by junedchhipa** 2020-01-16 15:46 UTC
Labels: xaxis
