### ISSUE TITLE
Negative values appear on y axis while every data-set has positive values

### ISSUE THREAD

**Issue by PixelWaxShop** [apexcharts/apexcharts.js#993] opened 2019-10-16 09:40 UTC
Example: [this codepen](https://codepen.io/PixelWaxShop/pen/OJJXpGg)

## Explanation

- What is the behavior you expect?

If there are no negative values in the dataset, ignore all negative values on the y-axis.

- What is happening instead?

I see negative values on the y-axis although there are no negative values in the dataset.

![image](https://user-images.githubusercontent.com/49190167/66907427-9d8ac500-f009-11e9-8000-37bbd65ca4ad.png)

- What error message are you getting?

I don't get any error.

**Comment by haroflow** [comment] 2019-10-21 19:22
I was having this problem and setting "min: 0" fixed it... which works for my needs.

**Comment by junedchhipa** [comment] 2019-12-15 07:24
Fixed in 3.11.0
Duplicate of #968, #614

**Closed by junedchhipa** 2019-12-15 07:24 UTC
Labels: bug
