### ISSUE TITLE
Horizontal scroll / Panning doesn't work on mobile

### ISSUE THREAD

**Issue by smemamian** [apexcharts/apexcharts.js#435] opened 2019-03-24 13:38 UTC
## Codepen
http://k.arflax.com/samples/react/line/chart.php?strkey=svFh2qsUc5ckz4MJjaNfS/BRK8cx6/gH&strdeviceid=654

## Explanation
`hand` icon on Iphone chrome doesn't appear.

![photo_2019-03-24_18-04-11](https://user-images.githubusercontent.com/2825656/54880186-ce35c200-4e5f-11e9-9bf3-4451aba4cc54.jpg)

**Comment by junedchhipa** [comment] 2019-03-24 14:45
Yes, zooming/panning is currently disabled on touch devices.
As we also need to show tooltips on single touch scroll, panning is disabled. Will find some workaround soon.

**Comment by junedchhipa** [comment] 2019-03-30 08:59
Closing as duplicate of #86

**Closed by junedchhipa** 2019-03-30 08:59 UTC

**Comment by ruudlaff** [comment] 2019-04-10 09:10
+1 to this, the panning/zoom buttons were a particular draw with this library as most charting libraries struggle with touch and the idea of using buttons seemed the logical conclusion. What about having left/right arrows on mobile rather than a pan button, with each click being a shift of 50% of the viewable area?

**Comment by rcoundon** [comment] 2020-01-12 21:58
Likewise, I'd like to see this implemented too

**Comment by darshanDevrai** [comment] 2020-07-28 15:50
@junedchhipa Any update for this feature???

**Comment by mspinelli** [comment] 2021-03-26 19:36
> Yes, zooming/panning is currently disabled on touch devices.
> As we also need to show tooltips on single touch scroll, panning is disabled. Will find some workaround soon.

Some of us may want to have tooltips disabled and have panning and zooming being the default behavior. Having the option to choose would be helpful!

**Comment by AleXSR700** [comment] 2022-08-12 13:35
+1

**Comment by mamun-devxhub** [comment] 2022-11-30 15:11
> +1

**Comment by Joe-Atteen** [comment] 2023-04-06 08:12
Any update on this?
