### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by KalinaStefanova** [apexcharts/apexcharts.js#3362] opened 2022-09-06 09:11 UTC
### Steps to Reproduce

1. Type https://apexcharts.com/ in any browser, or write "apexcharts" in google to find the website
2. Try to open the website

### Expected Behavior
To open the website 

### Actual Behavior 
<img width="1074" alt="Screenshot 2022-09-06 at 12 10 56" src="https://user-images.githubusercontent.com/12729059/188596008-73efa39e-6261-4414-917b-2f95cbd2749d.png">

**Comment by brianlagunas** [comment] 2022-09-06 13:32
Duplicate of #3212

**Closed by brianlagunas** 2022-09-06 13:32 UTC
Labels: bug
