### ISSUE TITLE
Zooming y-axis by main chart and x-axis by brush chart

### ISSUE THREAD

**Issue by wielski** [apexcharts/apexcharts.js#1360] opened 2020-03-05 16:19 UTC
# Bug report

## Codepen
Demo: https://codepen.io/wielski/pen/NWqazyy

## Explanation
I want to implement zooming by x-axis (datetime) by brush chart, and use main chart for zooming by y-axis.
When I trying to zoom from main chart with zoom type: 'y' it showing right stroke area, but zooming by x-axis instead.

**Comment by junedchhipa** [comment] 2020-03-07 12:42
Sorry, this is a limitation of using a brush chart with another chart. A brush chart is meant to be a handle for zooming into the main chart. Also, you may notice the resize handles on a brush chart supports only horizontal resize, disabling support for y-axis zooming.

Closing as it is not a bug, but a limitation of a brush chart.

**Closed by junedchhipa** 2020-03-07 12:42 UTC
