### ISSUE TITLE
Auto scale Y axis on zoom of x axis (Line graphs)

### ISSUE THREAD

**Issue by tomtelegraph** [apexcharts/apexcharts.js#542] opened 2019-04-24 09:09 UTC
Hi firstly this library is awesome!

I was wondering if it would be possible to add an option, so to auto scale the y axis of a time series(line graph) on zoom of only the x axis.

**Describe the solution you'd like**
If I have an outlier it can ruin the y axis for all other points. I would be prefect if the y axis would auto scale to the y axis values within the zoomed selection, when using only the X axis zoom.

**Describe alternatives you've considered**
Alternatively, would it be possible to implement a possitiveOnly option for the zoom options.chart.zoom.type: 'xy'. Which would prevent the user selecting an area on the negative side of the Y/X axis.

**Additional context**
Codepen detailing the outlier issue described above - https://codepen.io/T-Pullen/pen/wZpJJg

Thank you for taking the time!

**Comment by junedchhipa** [comment] 2019-04-24 09:30
Hi @tomtelegraph,
Thanks for the kind comment!

Regarding your suggestion of autoScaleYAxis, there was an attempt in the past to make it work, but unfortunately, it didn't work out great in multi-axis charts.

The option is `chart.zoom.autoScaleYaxis` located [here](https://github.com/apexcharts/apexcharts.js/blob/master/src/modules/ZoomPanSelection.js#L529) and is not production ready.
I will revisit that part and fix the multi-axis issue within it to make it production ready.

Thanks!

**Comment by junedchhipa** [comment] 2019-05-13 21:48
Closing as duplicate of #246

**Closed by junedchhipa** 2019-05-13 21:48 UTC
