### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by mdansari20101** [apexcharts/apexcharts.js#4681] opened 2024-09-04 06:17 UTC
Error when hovering over legends in Donut/Pie chart - "Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

There seems to be a bug in the Donut/Pie chart of ApexCharts. When hovering over the legend section, the following error is thrown:

"Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

This issue started occurring after a recent release. It was working perfectly before.

Steps to Reproduce:

1. Create a Donut/Pie chart using ApexCharts.
2. Hover over the legend section.
3. Observe the error in the console.

Expected Behavior: The chart should function without throwing errors when interacting with the legend.

Actual Behavior: Hovering over the legend results in the following error:
"Uncaught TypeError: Cannot read properties of undefined (reading 'toString')"

Additional Information:
This issue also occurs on the ApexCharts documentation example for the Donut chart.

Attached is a screenshot of the error for reference.

![Screenshot 2024-09-03 211456](https://github.com/user-attachments/assets/2dc8e9e4-7f1f-4e7d-b719-c0617e758919)

**Comment by brianlagunas** [comment] 2024-09-04 14:48
Duplicate of https://github.com/apexcharts/apexcharts.js/issues/4683

**Closed by brianlagunas** 2024-09-04 14:48 UTC
Labels: bug
