### ISSUE TITLE
Radial Bar chart label showing "series-1%"

### ISSUE THREAD

**Issue by paultargett** [apexcharts/apexcharts.js#1202] opened 2020-01-10 15:21 UTC
Hi we are seeing a problem with RadialBar charts showing the text "series-1%" that has appeared in the last 12 hours.

We are loading the javascript from the CDN: https://cdn.jsdelivr.net/npm/apexcharts

I think the error has started since the last update. There have been no changes in our code base.

Can you review please?

PT
<img width="181" alt="Screen Shot 2020-01-10 at 15 15 00" src="https://user-images.githubusercontent.com/7921210/72163896-941cb900-33bc-11ea-8fc5-c94fcfb01b41.png">

**Comment by junedchhipa** [comment] 2020-01-10 15:30
It is fixed in the latest release 3.13.1. Please wait for the next 24 hours for the CDN cache to clear.
Duplicate of #1200

**Closed by junedchhipa** 2020-01-10 15:30 UTC
