### ISSUE TITLE
Range Bar Chart

### ISSUE THREAD

**Issue by JoeyEff** [apexcharts/apexcharts.js#1142] opened 2019-12-17 00:26 UTC
Does the range bar chart support multiple colors? The snippet below works for the bar chart, but the range bar ignores the color section.

The bar chart that I tested on has one y value. That's the only difference.

<img width="509" alt="RangeBar" src="https://user-images.githubusercontent.com/1790195/70954143-2da8b300-2029-11ea-94b1-ea6e09e27e0f.PNG">

**Comment by junedchhipa** [comment] 2019-12-18 07:38
Duplicate of #1147

**Closed by junedchhipa** 2019-12-18 07:38 UTC
