### ISSUE TITLE
Tooltip display wrong color when fill: {type:"gradient"}

### ISSUE THREAD

**Issue by pgredigui** [apexcharts/apexcharts.js#3325] opened 2022-08-22 10:52 UTC
### Description

When I am usins a stacked bar chart and want to use a gradient fill property, the colour of the tooltip is wrong when I hover it. It always display the same colour (the one of the first element) instead of the colour of the element on which I am hovering (which is what it usually does)

### Steps to Reproduce

1.  create a stacked bar chart
2.  add in the options : {fill:{type:"gradient"}}
3. Hover your graph

### Expected Behavior

The colour of the tooltip should be the same as the one of the elements on which I am hovering 

### Screenshots

![Screenshot 2022-08-22 at 12 51 44](https://user-images.githubusercontent.com/66215803/185904410-b5d4bbba-bef7-40f9-b358-3c4f64fefafb.png)

### Reproduction Link

https://codepen.io/pgredigui/pen/JjLzNBv

**Comment by junedchhipa** [comment] 2024-10-11 12:41
duplicate of #4755

**Closed by junedchhipa** 2024-10-11 12:41 UTC
Labels: bug
