### ISSUE TITLE
Unable to see timestamp in CSV Production Environment

### ISSUE THREAD

**Issue by kazi86** [apexcharts/apexcharts.js#4573] opened 2024-07-18 05:02 UTC
![Local Envrionment](https://github.com/user-attachments/assets/a1132c49-7a75-4d23-8920-1d4381a05a6a)
![Production](https://github.com/user-attachments/assets/6970133e-1468-472a-827b-e250f1b36b9a)

@junedchhipa   I am unable to see the timestamp for chart-options given below for the production environment but it seems to be working fine for the local environment when i download csv the time stamp and date is visible as shown in files above.

export const realTimeMetricChartOptions: Partial<ChartOptions> = {
    series: [
        {
            name: 'Current Inventory',
            data: [],
            color: '#F7B84B',
        },
        {
            name: 'Flow Rate',
            data: [],
            color: '#0AB39C',
        },
    ],
    chart: {
        animations: {
            enabled: true,
            easing: 'easein',
            speed: 800,
        },
        height: 350,
        type: 'line',
        toolbar: {
            show: true,
            tools: {
                download: true,
                selection: true,
                zoom: true,
                zoomin: true,
                zoomout: true,
                pan: true,
                customIcons: [],
            },
            export: {
                csv: {
                    filename: "",
                    headerCategory: 'Date & Time',
                    headerValue: 'value',
                    dateFormatter(timestamp) {
                        return timestamp.toString().slice(0,25)
                    },
                },
                png: {
                    filename: ""
                }
            }
        },
        zoom: {
            enabled: true,
        },
    },
    dataLabels: {
        enabled: false,
    },
    grid: {
        show: false,
    },
    stroke: {
        curve: 'smooth',
        width: 2
    },
    xAxis: {
        type: 'datetime',
        labels: {
            datetimeUTC: false,
            datetimeFormatter: {
                day: 'dd MMM',
                hour: 'HH:mm '
            },
            style: {
                colors: '#ADB5BD',
                fontSize: '11px',
                fontWeight: '400',
                fontFamily: 'poppins',
            },
        },
    },
    yAxis: [
        {
            labels: inventoryLabelsSettings,
            title: {
                text: 'Inventory (gal)',
                style: textLabelStyle,
            },
            opposite: true,
            min: 0,
            axisBorder: {
                show: true,
                color: '#F7B84B',
                width: 1,
            },
            axisTicks: {
                show: true,
                color: '#ADB5BD',
            },
        },
        {
            labels: flowRateLabelSettings,
            title: {
                text: 'Flow rate (GPH)',
                style: textLabelStyle,
            },
            opposite: false,
            min: 0,
            axisBorder: {
                show: true,
                color: '#20B8A4',
                width: 1,
            },
            axisTicks: {
                show: true,
                color: '#ADB5BD',
            },
        },
    ],
    tooltip: {
        shared: true,

        x: {
            format: 'dd/MM/yy HH:mm ',
        },
        y: {
            formatter: function (y) {
                if (typeof y !== 'undefined') {
                    return y.toFixed(2) + '';
                }

                return y;
            },
        },
    },
    markers: {
        colors: ['#F7B84B', '#0AB39C'],

        hover: {
            size: 5,
        },
    },
    fill: {},
    legend: {
        show: true,
        onItemClick: {
            toggleDataSeries: false
        }
    }
};

**Comment by brianlagunas** [comment] 2024-07-18 16:29
Closing because the required reproduction link was not provided.

**Closed by brianlagunas** 2024-07-18 16:29 UTC
Labels: bug
