### ISSUE TITLE
Enabling multiple time ranges on timeline bar charts

### ISSUE THREAD

**Issue by stalnikar** [apexcharts/apexcharts.js#560] opened 2019-04-29 17:01 UTC
Requesting an enhancement on the current timeline bar charts (https://apexcharts.com/vue-chart-demos/bar-charts/timeline-chart/) so that multiple time ranges can be displayed. Attached sketch for reference.
![timeline](https://user-images.githubusercontent.com/29959553/56913140-b7d5e400-6a65-11e9-99b9-3fb9ae1430fc.jpeg)

**Comment by rtybanana** [comment] 2019-08-26 10:47
I'd also be interested in this being added. There are currently no vue integrated charting plugins which have this functionality.

**Comment by cjakeman** [comment] 2019-08-27 07:25
I'm working with a small team on a project that would greatly benefit from multiple time bars in the same horizontal slot. It's also using Vue.JS

**Comment by Shkiperon** [comment] 2019-09-19 10:43
Hi. Is it possible to make something like this by using existing version?

**Comment by bars949** [comment] 2019-09-24 10:01
Without this function, this view loses relevance in most cases. Someone was able to solve the standard functions?

**Comment by jakeflorentine** [comment] 2019-11-05 15:13
I also would find this feature rather useful. This project is great, and this capability would further separate it from other timelines.

**Comment by dylanmartin** [comment] 2019-11-12 16:42
The use case-described in OP is the sole motivation for me to try this library. Disappointing that it can't be implemented currently.

**Comment by junedchhipa** [comment] 2019-12-14 07:53
I have finished working on this and the functionality will be released in v3.11.0
I will also create demos for it on the website soon.

Thank you for your patience!

**Closed** 2019-12-14 07:52 UTC
Labels: enhancement, work-in-progress

**Comment by jakeflorentine** [comment] 2019-12-14 13:24
Juned,

I’m grateful for this addition!

Thanks,
Jake Florentine

**Comment by junedchhipa** [comment] 2019-12-14 14:29
Here are the demos - https://apexcharts.com/javascript-chart-demos/timeline-charts/

**Comment by thellimist** [comment] 2019-12-15 10:21
@junedchhipa thanks for the feature. I added another Test row
```
        {
          x: 'Test',
          y: [
            new Date('2019-03-08').getTime(),
            new Date('2019-03-12').getTime()
          ]
        },
```
Just in between two ranges. As you can see in the picture it looks like they are merged. This is not a wanted behaviour. 

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/6690196/70861351-857ee580-1f67-11ea-8507-7ebf74fc0e53.png">

**Comment by thellimist** [comment] 2019-12-15 10:25
@junedchhipa  another bug which I'm not sure if related with your changes but I'll add it to this issue. The colors in the labels are broken for custom colors

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/6690196/70861387-1eadfc00-1f68-11ea-921e-e5c4a1fae3ee.png">

**Comment by junedchhipa** [comment] 2019-12-15 10:30
> The colors in the legend are broken for custom colors

The colors of the legend don't correlate with each data item. It correlates with each series index.

You can override those colors with

```javascript
legend: {
  markers: {
    fillColors: ['purple', 'blue']
  }
}
```

**Comment by thellimist** [comment] 2019-12-15 11:00
> You can override those colors with

The issue is I have a dynamic rangeBar chart. The orders of the items might change. It can be hacked inserting random data to a time where the chart doesn't show to ensure it's order, however, the library should automatically handle this case in my opinion. That's what makes Apex Charts better than other alternatives. It is easy
