### ISSUE TITLE
Is there any option of fill in area between two datasets like chartjs?

### ISSUE THREAD

**Issue by saqibsra** [apexcharts/apexcharts.js#1113] opened 2019-12-05 12:34 UTC
Is there any option of fill in area between two datasets like chartjs?  because i implement Bollinger Band in my stock charts I done it in chartjs by using fill: +2 or 1 etc,

Is there any trick or option for doing this in apexcharts?

Here is chartjs link 
https://www.chartjs.org/docs/latest/charts/area.html

And here is my working code:
https://markets.brecorder.com/analyses/technical-analysis.html
You can check it by clicking Technical button and select Bollinger Band

Thanks in advance

Saqib

**Comment by junedchhipa** [comment] 2019-12-15 07:27
Not possible currently, but it is in the roadmap.
Duplicate of #184

**Closed by junedchhipa** 2019-12-15 07:27 UTC

**Comment by granthoff1107** [comment] 2021-03-23 22:36
what about using an area chart with negative values 
https://apexcharts.com/javascript-chart-demos/area-charts/negative/
