### ISSUE TITLE
Touch support for onMouseMove event Broken

### ISSUE THREAD

**Issue by zee0786** [apexcharts/apexcharts.js#4399] opened 2024-04-10 20:27 UTC
### Steps to Reproduce

1. Create a graph and open browser dev console with mobile view.
2. Try dragging graph crosshair across the data points

### Expected Behavior
the cross hairs should move 

### Actual Behavior
the cross hairs just crash and disappear when dragged

### Screenshots

working in 3.46.0 but broken in version 3.47.0
### Reproduction Link
https://ab0a-167-23-125-13.ngrok-free.app/

**Comment by brianlagunas** [comment] 2024-04-10 20:31
No need to create a new issue. I reopened the previous issue #4330 since you provided a reproduction. Closing this as a duplicate

**Closed by brianlagunas** 2024-04-10 20:31 UTC
Labels: bug
