### ISSUE TITLE
Empty tooltip displayed when you enter from the left side in a candlestick chart

### ISSUE THREAD

**Issue by daext** [apexcharts/apexcharts.js#1620] opened 2020-05-19 09:32 UTC
Hello,

the bug is visible on your demo page at https://apexcharts.com/javascript-chart-demos/candlestick-charts/combo/

To reproduce the issue you have to:

1. Reload the page
2. Enter from the left side of the chart e position the cursor on the yaxis labels
3. If you enter in the actual chart area the bug disappears and you have to reload the page to see it again

If you also have a solution to temporarily fix it would be appreciated.

![image](https://user-images.githubusercontent.com/7547692/82309857-a7a2e680-9991-11ea-85a1-eb0744dc7d86.png)

**Comment by Thimows** [comment] 2020-05-21 10:33
I noticed that this happens with all the charts that uses Y- and X-axis.

**Comment by paulovpereira** [comment] 2020-11-03 10:15
+1 / Noticed same issue

**Comment by eternalsayed** [comment] 2020-11-05 12:27
+1
Same issue with multiple y-axes (4 in my case, wherein 3, on the same side, have same min-max while the one on other side has different ranges.

**Comment by agaluf** [comment] 2021-05-10 10:28
I can confirm this bug is reproducible on a line chart where the first data point in the series is null. On hover, the tooltip is marked as active, which sets its opacity to 1, while the tooltip title is empty, but not hidden with display: none like the content. As soon as a valid data point is selected, the tooltip is correctly filled. On mouse blur, the tooltip contents are preserved, meaning the tooltip will show data on next mouseover.

Note how both series-groups are hidden, but the title is not:

![image](https://user-images.githubusercontent.com/6173626/117644944-4ec3f380-b18a-11eb-8b1a-4cf74da8edfc.png)

I see two possible solutions to this problem:

1. hide the title just as the series is hidden and only show it when it contains any data
2. display the tooltip only when the data point exists.

A temporary hack to this bug: use the following css:

```css
.apexcharts-tooltip-title:empty {
  display: none;
}
```
This hides the tooltip title when its value is empty. It doesn't work 100%, as a small grey dot will still be visible, but most people won't notice it.

**Comment by rishabhtatia1** [comment] 2021-05-13 06:29
It is happening due to tooltip having some padding or height so if you remove that then the dot is not visible
.apexcharts-tooltip-title:empty {
  display: none;
}
After applying this

**Comment by vaishali-shm** [comment] 2021-06-23 10:23
+1,Still facing this issue for line chart,& css fix does not work everytime we hover on chart.

**Comment by paulovpereira** [comment] 2021-10-11 08:54
It's still happening.

**Comment by eternalsayed** [comment] 2021-12-28 15:31
Can we have a fix for this?

**Comment by junedchhipa** [comment] 2022-01-01 10:59
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/a39fd943a9680a672a786ddf9db8160c1a977d02)
A new version will be released soon.

**Closed by junedchhipa** 2022-01-01 10:59 UTC
