### ISSUE TITLE
Cannot read property 'tickInterval' of undefined

### ISSUE THREAD

**Issue by ligiaandreica** [apexcharts/apexcharts.js#1868] opened 2020-08-28 13:43 UTC
# Bug report
After upgrading from 3.19.3 to 3.20.0, I've started getting `Cannot read property 'tickInterval' of undefined` when setting `showDuplicates` to `false` for `labels` in an area chart.

## Codepen
https://codesandbox.io/s/react-basic-example-forked-5s0lh?file=/src/App.js

```import React, { Component } from "react";
import Chart from "react-apexcharts";

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      options: {
        chart: {
          id: "basic-bar"
        },
        xaxis: {
          labels: {
            showDuplicates: false, // causes error
          },
          categories: [1991, 1991, 1991, 1991, 1991, 1991, 1997, 1998]
        }
      },
      series: [
        {
          name: "series-1",
          data: [30, 40, 45, 50, 49, 60, 70, 91]
        }
      ]
    };
  }

  render() {
    return (
      <div className="app">
        <div className="row">
          <div className="mixed-chart">
            <Chart
              options={this.state.options}
              series={this.state.series}
              type="area"
              width="500"
            />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
```

## Explanation

- What is the behavior you expect?
Should see x axis labels without duplication.

- What is happening instead?
Getting `Cannot read property 'tickInterval' of undefined` error

- What error message are you getting?
![image](https://user-images.githubusercontent.com/59609285/91566820-1e119600-e93c-11ea-8ebd-12bb939a11b0.png)

**Comment by junedchhipa** [comment] 2020-08-31 14:31
Duplicate of #1729 
It's already fixed. The patch will be released soon.

**Closed by junedchhipa** 2020-08-31 14:31 UTC
