### ISSUE TITLE
Cropped x-axis labels when legend is on the right

### ISSUE THREAD

**Issue by pribilinskiy** [apexcharts/apexcharts.js#125] opened 2018-09-24 06:18 UTC
When legend position is `right` the x-axis labels on the bottom are cropped

https://codepen.io/anon/pen/gdJYZb

**Comment by junedchhipa** [comment] 2018-09-25 06:13
Can you provide a better example?
Can’t see in your demo

**Comment by pribilinskiy** [comment] 2018-09-25 09:04
![image](https://user-images.githubusercontent.com/3078595/46004248-13e51e00-c0bb-11e8-9292-847afb894f91.png)

**Comment by junedchhipa** [comment] 2018-09-25 14:39
Thanks, I was not seeing this on chrome (mac). I will check in other browsers.

**Comment by junedchhipa** [comment] 2018-09-27 17:29
Checked in Chrome / Firefox / Safari on Mac - couldn't reproduce the issue.
Are you on Windows? If yes, which browser?

**Comment by pribilinskiy** [comment] 2018-09-27 17:35
@junedchhipa It's in Chrome on Ubuntu 18. Probably because of different default local font
On Windows it's ok indeed.
![image](https://user-images.githubusercontent.com/3078595/46163763-b73d5b00-c294-11e8-86e7-3f7747d96c2e.png)

**Comment by junedchhipa** [comment] 2018-09-27 17:38
Ok, thanks for the info. I will add some small paddings based on fontSize

**Comment by pribilinskiy** [comment] 2018-10-02 11:00
Upgraded to 2.0.6, labels are still (or even more) cropped
![image](https://user-images.githubusercontent.com/3078595/46344941-71ddac80-c64b-11e8-83e0-2286b8b1ab62.png)

**Comment by junedchhipa** [comment] 2018-10-02 11:02
Yes, this is still not worked upon.
You will have to wait for the next version ;)

**Closed** 2018-10-02 11:40 UTC

**Comment by junedchhipa** [comment] 2018-10-05 21:40
I have made a 10px offset when the legend is on right, but couldn't really test on Ubuntu.
Let me know if v2.0.9 fixes it.

**Comment by pribilinskiy** [comment] 2018-10-06 08:19
@junedchhipa that fixed it, finally! Thanks!
