### ISSUE TITLE
 A negative value appears on the Y axis when each data set has a positive value

### ISSUE THREAD

**Issue by C3maLi** [apexcharts/apexcharts.js#775] opened 2019-07-19 08:45 UTC
## Codepen
https://codepen.io/CemaLi/pen/zgxZzp

## Explanation
- What is the behavior you expect?
1. Negative values ​​appear on the Y axis even though there are no negative values ​​in the data sets.
2. The tooltip appears when the last two elements in the graph or the elements in other positions are not available (chart type: line, series type: column.)

- What is happening instead?
1. I don't want to see negative values ​​on the Y Axis
2. Hiding tooltips of elements without values

- What error message are you getting?
I am not receiving an error message.

thank you.

**Comment by aymericaitamer** [comment] 2019-10-12 14:58
+1

**Comment by reynom** [comment] 2019-10-30 20:26
+1

**Comment by z1m1n** [comment] 2019-11-12 09:26
```
yaxis: {
   min: 0,
   forceNiceScale: true,
}
```
Works for me.

https://codepen.io/zimon/pen/VwwGwVw

**Comment by junedchhipa** [comment] 2019-12-17 17:45
Fixed in 3.11.0
Duplicate of #968, #614

**Closed by junedchhipa** 2019-12-17 17:45 UTC
