### ISSUE TITLE
zoom problem in realtime chart

### ISSUE THREAD

**Issue by Sumon-miazi** [apexcharts/apexcharts.js#886] opened 2019-09-02 17:10 UTC
for realtime data append the zoom feature is not working as expected. I used **appendData** method to add data.used  **window.setInterval(function () {...}, 1000);** function. is there any way to stabilize the zoom while data is updating? 
tried different values(2s,5s,10s... etc) as time interval but not working.

![deepin-screen-recorder_Select area_20190902225040](https://user-images.githubusercontent.com/28239287/64128104-a4050a80-cdd6-11e9-8299-e81aa869c8f2.gif)

Thanks for your attention. I’m looking forward to your reply.

**Comment by junedchhipa** [comment] 2019-09-03 09:16
Yeah, that's a bug which is still not fixed.
Closing this as duplicate of #643

**Closed by junedchhipa** 2019-09-03 09:16 UTC
