### ISSUE TITLE
Stacked Column Charts misaligned labels and x-axis dashes

### ISSUE THREAD

**Issue by ericfrancisco** [apexcharts/apexcharts.js#933] opened 2019-09-24 14:44 UTC
This appears to be broken on js and vue examples.

https://apexcharts.com/vue-chart-demos/column-charts/stacked/

<img width="693" alt="Screen Shot 2019-09-24 at 10 42 30 AM" src="https://user-images.githubusercontent.com/3536206/65522037-25245e80-deb8-11e9-9a73-0daed8aab2cc.png">

**Comment by mattlam** [comment] 2019-10-06 07:20
If it helps, the issue seems to be related to the dateTime functionality.

Once the datetime option is removed, everything centers as expected.

Here's the codepen https://codepen.io/matthlamers/project/editor/APWgzK 
type: 'datetime',

**Comment by junedchhipa** [comment] 2020-01-18 13:35
The issue isn't reproducible anymore in the latest versions (as of now 3.15.2)
Hence, closing it.

**Closed by junedchhipa** 2020-01-18 13:35 UTC
Labels: bug
