### ISSUE TITLE
Empty tooltip and console errors when setting 'between' for xAxis.tickPlacement on line charts

### ISSUE THREAD

**Issue by nikkorn** [apexcharts/apexcharts.js#3521] opened 2022-11-28 15:34 UTC
### Description
When rendering a line chart by setting the chart type of 'line' on the data series object and then setting 'between' for xAxis.tickPlacement causes errors (Uncaught TypeError: Cannot read properties of undefined (reading '0')) to be shown in the console and a blank tooltip to be shown when hovering to the right of the last data point on the chart.

It looks like it might be trying to create a tooltip for the next category, which doesn't exist.

### Steps to Reproduce
1. Create a chart definition where the chart type of 'line' is assigned to the series object and not object.chart.type.
2. Set tickPlacement to be "between" for the x axis.
3. Hover over the area to the right of the last data point.

### Expected Behavior
The tooltip for the last data point should still be shown.

### Actual Behavior
An empty tooltip is shown and the console is flooded with errors.

### Screenshots
https://i.imgur.com/nrujwTZ.png

### Reproduction Link
https://codepen.io/nikkorn/pen/BaVPzYq

**Comment by nicobatalla** [comment] 2022-11-28 23:59
I think this may be a regression on `v3.36.3`

We are getting the same  `(Uncaught TypeError: Cannot read properties of undefined (reading '0'))` error on charts that were working fine on previous versions, and no changes on our side whatsoever.

`3.36.0` was working fine

**Comment by nikkorn** [comment] 2023-01-04 13:57
Hmmm i've been able to reproduce this on both 3.36.0 and 3.35.0 using my steps, maybe it's been around for a while

**Comment by rodericktech** [comment] 2023-04-12 14:37
Also seeing this now on our charts with 'between' ticks on the X axis.  I went from 3.37.x back as far as 3.34.x to test just now and the console errors were still happening, which is odd ... I've been using Apex on a couple of React projects for almost two years and it's only in roughly the last few weeks that I (or any of the other devs on this team) have seen this happening with our charts.

I don't have a solution for this but it looks like a PR to address the issue was already contributed (and then auto-closed last month).  I am commenting here just to add another "yes, this issue is still occurring" voice.  If any of you in this thread have come up with a solution for this already (outside of the closed PR) I would be grateful to know.

**Comment by SoonGwan** [comment] 2023-04-12 15:35
Ah... I'm having the exact same problem you're describing.
I'm using version 3.37.3.

**Comment by junedchhipa** [comment] 2024-08-27 11:39
This is fixed in v3.48.0

**Closed by junedchhipa** 2024-08-27 11:39 UTC
Labels: bug
