### ISSUE TITLE
Duplicate x axis labels

### ISSUE THREAD

**Issue by ThinkSalat** [apexcharts/apexcharts.js#548] opened 2019-04-25 22:52 UTC
# Explanation
See picture
![Screen Shot 2019-04-25 at 3 49 53 PM](https://user-images.githubusercontent.com/31082405/56773180-f0c63e00-6771-11e9-8f76-daa212be1e48.png)

Any way to fix this? It happens so often and I don't see any way to manage this in the xaxis chart options. Does this happen to anyone else?

**Comment by junedchhipa** [comment] 2019-04-26 05:15
Full codepen example, please?

**Comment by ThinkSalat** [comment] 2019-04-29 16:50
I couldn't get a codepen to reproduce but how would I debug this? It seems like a bug in the charting library, not my config.

**Comment by junedchhipa** [comment] 2019-04-29 16:52
Yes, indeed it's a bug, not the config issue.
I just need the series so I can paste and reproduce it easily.

I'm assuming some values like below

```javascript
series: [{
  data: [4, 4, 3, 3, 3, 0, 0, 0]
}]
```

**Comment by ThinkSalat** [comment] 2019-04-30 18:56
Ahh... Gotcha. here's what's in my series:

[{
  "name": "Severity",
  "data": [{
    "x": "Custom Symptom",
    "y": 4
  }, {
    "x": "Custom 2",
    "y": 4
  }, {
    "x": "Difficulty with self-care - activities in daily living",
    "y": 3
  }, {
    "x": "Decreased need for sleep",
    "y": 3
  }, {
    "x": "Abdominal pain",
    "y": 3
  }, {
    "x": "Depersonalization (experiences of unreality or detachment with respect to oneself)",
    "y": 0
  }, {
    "x": "Hostility (anger or irritability in response to others, or mean, nasty, or vengeful behaviors)",
    "y": 0
  }, {
    "x": "Difficulty with self-care - safety",
    "y": 0
  }, {
    "x": "Hyperactivity",
    "y": 0
  }, {
    "x": "Does not comply or obey (in appropriate or expectable context)",
    "y": 0
  }, {
    "x": "Excessive sexual behavior or preoccupation",
    "y": 0
  }, {
    "x": "Unusual response to sensory input (lights, sounds, textures, odors)",
    "y": 0
  }, {
    "x": "Social Anxiety (anxious, worried, or nervous about social situations)",
    "y": 0
  }, {
    "x": "Difficulty recognizing shapes and patterns",
    "y": 0
  }, {
    "x": "Complex motor tic",
    "y": 0
  }]
}]

**Comment by junedchhipa** [comment] 2019-05-04 07:20
I am not able to reproduce the duplicate labels issue with your series.
![Screen Shot 2019-05-04 at 12 49 56 PM](https://user-images.githubusercontent.com/17950663/57175564-2f8f7e80-6e6b-11e9-9317-74c4a31a0ad0.png)

Maybe try changing the `xaxis.tickAmount` and see if it works.

**Comment by ThinkSalat** [comment] 2019-05-06 19:34
I tried changing the tickAmount and it didn't change anything. I changed it to 0 and I changed it to 5 and I changed it to 100000000

**Comment by ThinkSalat** [comment] 2019-05-06 19:35
These kind of issues have been happening a lot, so it's not just a one time thing. Can you point me in the right direction on how to fix this?

**Comment by junedchhipa** [comment] 2019-05-06 23:11
I would appreciate a full codepen example so I can directly jump to the main issue.

**Comment by ThinkSalat** [comment] 2019-05-07 17:38
I tried but for some reason I couldn't replicate the issue. I've been spending a long time on this and all our charts use react-apex-charts.

**Comment by junedchhipa** [comment] 2019-05-13 21:58
Without a working codepen demo, I am unable to locate the cause of the issue.
Can you check which versions of `apexcharts` and `react-apexcharts` are you using?

**Comment by ThinkSalat** [comment] 2019-05-17 16:58
I am on apexcharts 2.6.0 and react-apexcharts 1.3.0

**Comment by ThinkSalat** [comment] 2019-05-17 17:17
Is there any way to hard code the x axis just as a temporary fix?

**Comment by junedchhipa** [comment] 2019-05-17 20:21
Can you please upgrade to apexchart@3.6.11 which is the latest version right now?

**Comment by junedchhipa** [comment] 2019-05-18 21:54
Closing this as this has already fixed in the current version - `apexcharts@3.6.11`
Feel free to re-open if the latest version doesn't fix the issue.

**Closed by junedchhipa** 2019-05-18 21:54 UTC

**Comment by lloydlim** [comment] 2022-06-15 06:46
apexchart v3.35.3
@junedchhipa Encounter the issue on above version

![image](https://user-images.githubusercontent.com/19586777/173758939-e4f1d587-769c-440e-ae6e-b91810ad024b.png)

https://codepen.io/lloydlim/pen/PoQVRaY

**Comment by fpegios** [comment] 2022-09-13 09:41
I am facing the same issue in 3.28.1 using react-apexcharts.

**Comment by shashankgupta2703** [comment] 2022-10-10 04:21
![%7Bb4497306-12b4-4b0a-ab15-cadc5edfbc00%7D](https://user-images.githubusercontent.com/104415719/194798862-86ee57f0-26b9-4006-9e1d-83b36b787d05.png)
facing duplicate dates in xaxis.

**Comment by Mr-MooMoo** [comment] 2024-03-28 08:27
Facing the same issue with Blazor-ApexCharts 3.1.0

**Comment by MaxGonzalez67304** [comment] 2024-09-19 15:30
Same issue with apexcharts@3.49.1 and ng-apexcharts@1.10.0, solved it using tickAmount on xaxis
