### ISSUE TITLE
Chart height increases whenever the windows is resized when we use `height: '100%'`

### ISSUE THREAD

**Issue by mrahhal** [apexcharts/apexcharts.js#2059] opened 2020-11-21 13:14 UTC
# Bug report

## Codepen

Here is the [codepen](https://codepen.io/mrahhal/pen/ZEOdaRN).

## Explanation

When we have `height: '100%'`, whenever the window is resized the chart height increases. You can see this in the codepen above by simply restoring down/maximizing the browser or by resizing the window.
In my own app, the height keeps on increasing forever after the first resize, I couldn't repro this in the codepen. Here's a gif of the problem from my app:

![jIqe4xsfgl](https://user-images.githubusercontent.com/4404199/99878155-16e0e800-2c0c-11eb-88fd-4a73ff3977ca.gif)

I know that there's this in the docs:
```
Note: If you provide a percentage value '100%', make sure to have a fixed height parent.
```

But isn't using flex like that supposed to work? There's no way I can give an explicit height to the parent, this just isn't feasible when doing flexible layouts.

**Comment by junedchhipa** [comment] 2020-11-21 14:00
Put the chart in a fixed height container and then apply `height: 100%`

```html
<div class="chart-wrap">
  <div class="chart"></div>
</div>
```

```css
.chart-wrap {
  height: 300px
}
```

**Comment by junedchhipa** [comment] 2020-11-21 14:01
Duplicate of #1609

**Comment by mrahhal** [comment] 2020-11-21 16:16
I understand closing this directly as a duplicate, but I've seen the other 2 issues and there's no real viable solution when you're working in flex here. Putting an explicit height on the direct parent is an absolute no-go in many situations. There's a height in some distant parent, but definitely not the direct parent when you're doing any kind of non-simple layouts. And in these kinds of layouts you're usually doing idiomatic flex. **Idiomatic flex code doesn't work**, which is the source of my frustration. 

I found a solution that seems to be working. I have a hierarchy where the element that has a height is far above the chart. What worked is making the graph absolute and fill the flex parent. Here's an example for when you have a flex wrap cards kind of layout, and you have a graph far down in the card:

```scss
.some-distant-parent-container {
  display: flex;
  flex-flow: wrap;
}

.some-distant-parent-card {
  height: 200px;
  display: flex;
  flex-flow: column;
}

.direct-parent {
  flex: 1;
  position: relative;
  min-width: 400px;
}

// I'm using angular
.direct-parent > apx-chart {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

**Comment by junedchhipa** [comment] 2020-11-21 16:22
Ok, your original questions didn't have this information (using flex), hence I closed it marking it as duplicate.
Given your additional context, I am re-opening it and looking further.

**Comment by junedchhipa** [comment] 2020-11-21 16:38
Can you try this?

```js
options = {
  chart: {
    parentHeightOffset: 0
  }
}
```

I guess, this is the culprit, and setting this to 0 fixes it.

**Closed** 2020-11-21 17:09 UTC

**Comment by mrahhal** [comment] 2020-11-21 18:17
Thank you for reopening. I see that you've added a commit that fixes this. I'll try it when you release a new version and will come back and report if it also works in my particular case, since I have a complex layout.

**Comment by junedchhipa** [comment] 2020-11-21 18:20
Sure, I have fixed it by removing minHeight when the height is '100%'.

In case, there is not enough padding at the bottom of the chart, you will have to manually add some padding. This will be the only caveat when using `height: 100%`

**Comment by Wsxder** [comment] 2022-08-09 08:24
Hello, I still have this issue. I have parent container set to fixed height of 40vh and charts height set to 100% and It is still growing in size. The property min-height is still there and is probably causing the problem. I am using version 3.35.0.

**Comment by Wsxder** [comment] 2022-08-11 07:58
@junedchhipa
