### ISSUE TITLE
Radial Bar Chart - Label Issue

### ISSUE THREAD

**Issue by tim9192** [apexcharts/apexcharts.js#1200] opened 2020-01-10 11:16 UTC
## Explanation

**- What is the behavior you expect?**

The label value should be shown in the chart.

**- What is happening instead?**

The chart shows "series-1%" instead of the given label.

[Codepen example](https://codepen.io/tim9192/pen/BayxBgG)

or just look in the docs of the radial bar charts, where the issue is also present.

**Comment by junedchhipa** [comment] 2020-01-10 12:29
Please upgrade to v3.13.1
The issue is fixed in the latest version

**Closed by junedchhipa** 2020-01-10 12:29 UTC
