### ISSUE TITLE
502 Bad gateway error

### ISSUE THREAD

**Issue by Agus-Wei** [apexcharts/apexcharts.js#4617] opened 2024-08-03 14:23 UTC
Could not access https://apexcharts.com/docs/options/chart/type/. Got bad gateway error
![image](https://github.com/user-attachments/assets/0772270e-c600-4af6-a8e4-d07d0e16741b)

**Comment by junedchhipa** [comment] 2024-08-03 19:07
Duplicate of #4613

**Closed by junedchhipa** 2024-08-03 19:07 UTC

**Comment by KalanaPerera** [comment] 2024-08-04 07:11
still down

**Comment by HermanCeaser** [comment] 2024-08-04 20:51
This is still the case as of Aug 4 23:45. What is happening?
