### ISSUE TITLE
(VueApexCharts) Unable to assign an array to xaxis['categories']

### ISSUE THREAD

**Issue by mattilind** [apexcharts/apexcharts.js#407] opened 2019-03-17 12:06 UTC
I have a function that I use for building the optionsObject. 
![code2](https://user-images.githubusercontent.com/48258345/54490329-8a6e1600-48bd-11e9-80c7-560b639a98ba.PNG)
Even tried this with static array with no luck (dates were in the correct format). 
![optionsObject](https://user-images.githubusercontent.com/48258345/54490141-fe0f2380-48bb-11e9-863a-2f7c2ae2dcdc.PNG)
Here is the actual error I'm getting (which is probably because the categories array is empty, but anyway).
![error](https://user-images.githubusercontent.com/48258345/54490147-0cf5d600-48bc-11e9-93bf-d196e114da6f.PNG)

One more interesting thing to note was that a colleague of mine who installed this project with all it's dependencies had it working just fine (no errors, no problems in zooming). And it works fine in production. So this bug might not be entirely ApexCharts related, but something weird seems to be going on here. :P

Using Lubuntu 16.04, vue@3.4.1 and vuetify@1.5.5.

Also tried this with no luck: 
![code](https://user-images.githubusercontent.com/48258345/54490343-ab366b80-48bd-11e9-8ec6-0157eaccd1af.PNG)

**Comment by mattilind** [comment] 2019-03-17 12:15
This should have been in VueApexCharts, sorry!

**Comment by junedchhipa** [comment] 2019-03-17 14:06
CLosing as the duplicate of https://github.com/apexcharts/vue-apexcharts/issues/76

**Closed by junedchhipa** 2019-03-17 14:06 UTC
