### ISSUE TITLE
Points vanishing when disabling some lines via label click

### ISSUE THREAD

**Issue by Connum** [apexcharts/apexcharts.js#1428] opened 2020-03-25 13:48 UTC
# Bug report

## Codepen
No Codepen needed, also occurs in the demo at https://apexcharts.com/javascript-chart-demos/line-charts/null-values/

## Explanation
On first load, with all lines being displayed, points show up fine on hover for all lines.

Click the "Peter" label to hide the blue line. Hover a point on the yellow line, e.g. at x value 7:
![grafik](https://user-images.githubusercontent.com/13076806/77542851-1d656700-6ea7-11ea-989e-a9b294f9327c.png)
The point on the yellow line is not showing, only the one on the cyan line.

Show "Peter" again, hide "Jonny":
![grafik](https://user-images.githubusercontent.com/13076806/77543015-54d41380-6ea7-11ea-8c91-3f55a774295b.png)
Points are shown on both lines (though with their colors swapped, see #1427).

If you show only either the "Peter" or "David" line, there will be no points shown on hover. However, for the "Jonny" line, the points will always work.

**Comment by Connum** [comment] 2020-03-25 15:07
The issue vanishes when setting the `markers` option to a value > 0.

**Comment by junedchhipa** [comment] 2020-03-25 16:49
Which version of apexcharts are you using? I cannot reproduce this with the latest version.

**Comment by Connum** [comment] 2020-03-25 17:15
Latest version from npm, but as I said it also occurs in the demo (tested with Firefox latest, Windows).

**Comment by junedchhipa** [comment] 2020-03-25 17:17
Ah! I was checking in chrome.
It will be addressed soon.

**Comment by junedchhipa** [comment] 2024-12-27 17:07
Fixed with this [commit](https://github.com/apexcharts/apexcharts.js/commit/a6cefdcdddf6430bce47edf937b974d22dd65a5a)

**Closed by junedchhipa** 2024-12-27 17:07 UTC
Labels: bug, markers
