### ISSUE TITLE
Donut chart legend and tooltip markers don't show when using colors function

### ISSUE THREAD

**Issue by ryinyang** [apexcharts/apexcharts.js#1450] opened 2020-03-31 01:37 UTC
# Bug report

## Codepen

https://codesandbox.io/s/falling-sun-jxedu

## Explanation

- What is the behavior you expect?

  - I'm expecting the tooltip color and the legend marker to have the same color as the donut slice when using a function to render color.

- What is happening instead?

  - The tooltip is black instead of the matching slice's color. The legend's marker is either white or not showing.

- What error message are you getting?

  - No error messages.

## What I've tried

Following #725 and [documentation](https://apexcharts.com/docs/options/colors/), I tried using the overrides in `tooltip.marker.fillColors` & `legend.markers.fillColors`. This did not fix my issue.

## Current work-around

I'll be hard coding the colors array for the time being.

**Comment by junedchhipa** [comment] 2020-03-31 12:58
Thanks for reporting.
The issue is [fixed](https://github.com/apexcharts/apexcharts.js/commit/d0a90ff564e2601d01cac8d786f23686d6178f61) but it is not released to npm yet. A new version (3.18.0) will be released soon this weekend.

**Closed by junedchhipa** 2020-03-31 12:58 UTC
Labels: bug
