### ISSUE TITLE
Line chart - labels on the x axis not rendering properly

### ISSUE THREAD

**Issue by ortigozamatias** [apexcharts/apexcharts.js#509] opened 2019-04-02 19:18 UTC
Hi! I have a line chart whose x axis is of datetime type, showing a formatted hour. The problem is that the last label is not showing itself complete. 

<img width="874" alt="Screen Shot 2019-04-02 at 3 32 04 PM" src="https://user-images.githubusercontent.com/18308689/55427681-e4c5d280-555d-11e9-815d-041526d61d02.png">

I've tried to avoid using any padding or margin but haven't found a solution so far.

Here is the code for the chart:

```javascript
export default memo(function LineChart(props) {
    const maxY = useMemo(() => max(props.data) + 1);
    const chartOptions = {
        options: {
            plotOptions: { line: { curve: 'smooth' } },
            chart: {
                animations: { speed: 1500 },
                toolbar: {
                    tools: {
                        download: false,
                        selection: true,
                        zoom: '<img src="/icons/zoom_in.svg" width="20">',
                        zoomin: '<img src="/icons/plus_circle.svg" width="20">',
                        zoomout: '<img src="/icons/minus_circle.svg" width="20">',
                        pan: '<img src="/icons/grab.svg" width="20">',
                        reset: '<img src="/icons/home.svg" width="20">'
                    },
                    autoSelected: 'zoom'
                },
            },
            colors: [colors.contentBackground],
            stroke: {
                width: 5,
                curve: 'smooth'
            },
            xaxis: {
                type: props.type,
                labels: {
                    style: { colors: colors.contentBackground },
                    formatter: value => {
                        const categoryTime = new Date(value);
                        const hours = categoryTime.getHours();
                        const minutes = categoryTime.getMinutes();
                        const minutesString = minutes === 0
                            ? `${minutes}0`
                            : minutes < 10
                                ? `0${minutes}`
                                : minutes;
                        const seconds = categoryTime.getSeconds();
                        const secondsString = seconds === 0
                            ? `${seconds}0`
                            : seconds < 10
                                ? `0${seconds}`
                                : seconds;

                        return `${hours}:${minutesString}:${secondsString}`;
                    }
                },
                axisBorder: { color: colors.contentBackground },
                axisTicks: { color: colors.contentBackground },
                tooltip: { enabled: false },
                crosshairs: { stroke: { color: colors.darkGreen } },
                categories: props.categories
            },
            tooltip: { x: { format: 'dd MMM HH:mm:ss' } },
            yaxis: {
                min: 0,
                max: maxY,
                labels: { style: { color: colors.contentBackground } },
                axisBorder: { color: colors.contentBackground },
                axisTicks: { color: colors.contentBackground },
            },
            markers: {
                size: 4,
                opacity: 1,
                colors: [colors.contentBackground],
                strokeWidth: 0,
                hover: { size: 7 }
            }
        },
        series: [{
            name: props.dataName,
            data: props.data
        }]
    };

    return <Chart options={chartOptions.options} series={chartOptions.series} type="line" height={props.height} />;
});
```

Here is the data and categories payload:

<img width="1674" alt="Screen Shot 2019-04-02 at 4 14 15 PM" src="https://user-images.githubusercontent.com/18308689/55429813-b7c7ee80-5562-11e9-9750-0a13c77f19eb.png">

Thanks!

**Comment by junedchhipa** [comment] 2019-04-14 18:28
Closing this as it is a duplicate of #305 
I will take a look soon.

**Closed by junedchhipa** 2019-04-14 18:28 UTC
