### ISSUE TITLE
Bubble Chart: Should allow for a minimum bubble size

### ISSUE THREAD

**Issue by BiggerNoise** [apexcharts/apexcharts.js#1024] opened 2019-10-25 14:28 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to display bubbles with Z values in the range [0,1]. If the Z value is 0, then no bubble is drawn at all. 

**Describe the solution you'd like**
Ideally, I'd be able to set a minimum size and the drawn radius would never shrink below that.

**Describe alternatives you've considered**
As a workaround, I am banding my data into quintile buckets and sending a value for the bucket. E.g., [0,.2] gets 1, (.2,.4] gets 2, etc.. Use the actual values to format a custom tooltip.

**Comment by junedchhipa** [comment] 2019-10-26 20:14
Duplicate of #604 
Thread continued in #604

**Closed by junedchhipa** 2019-10-26 20:14 UTC
