### ISSUE TITLE
Sparklines bar type chart's tooltip misplaced

### ISSUE THREAD

**Issue by arkhenstone** [apexcharts/apexcharts.js#106] opened 2018-09-16 16:46 UTC
Tooltips just don't care of their surrounding, always sticking to their default positions with sparkllines bar. The fixed property don't work at all. Works just as intended with line.

See image below. Even the further at left display the tooltip at the left.

![bug](https://user-images.githubusercontent.com/17592744/45598732-fcce6e00-b9e0-11e8-922d-a6140d8f91ad.png)

**Comment by junedchhipa** [comment] 2018-09-27 17:41
Closing this as cannot reproduce the issue

**Closed by junedchhipa** 2018-09-27 17:41 UTC
