### ISSUE TITLE
Multiple Y-Axis in demo on apexcharts.com is broken

### ISSUE THREAD

**Issue by jasonpolites** [apexcharts/apexcharts.js#4563] opened 2024-07-10 05:38 UTC
### Description

The demo chart on the apexcharts website for the "Multiple Y-Axis" chart is broken

https://apexcharts.com/javascript-chart-demos/mixed-charts/multiple-yaxis/

Attempting to run it locally reveals this error in the dev console:

```console
TypeError: Cannot read properties of undefined (reading 'group')
    at apexcharts:6:168003
    at Array.forEach (<anonymous>)
    at apexcharts:6:167964
    at Array.forEach (<anonymous>)
```

**Comment by rosco54** [comment] 2024-07-11 05:15
There are no series defined:
`series: []`
 
This same thing happened in another demo chart recently with the same result.

**Comment by junedchhipa** [comment] 2024-07-12 07:41
Duplicate of #4492

**Closed by junedchhipa** 2024-07-12 07:41 UTC
Labels: doc
