### ISSUE TITLE
Connect values between null points in Line Chart.

### ISSUE THREAD

**Issue by jofftiquez** [apexcharts/apexcharts.js#747] opened 2019-07-07 04:56 UTC
**Is your feature request related to a problem? Please describe.**
I am using apex chart to map a series of data that might potentially have `null` values in them. I found this example quite helpful https://apexcharts.com/vue-chart-demos/line-charts/, however, I need to connect the values between `null` points.

**Describe the solution you'd like**
An extra boolean option to connect the values between `null` points like, `spanGaps` similar to [spanGaps](https://www.chartjs.org/docs/latest/charts/line.html#line-styling) in ChartJs.

**Additional context**

Given the data `[1, null, 3, 4]`. The result is the image below.

![Imgur](https://i.imgur.com/cNk20Oh.jpg)

**Comment by junedchhipa** [comment] 2019-07-08 19:16
This has been proposed, but not worked upon yet.
Closing as duplicate of #146

**Comment by cseelus** [comment] 2019-09-03 11:48
Similar to #146, but I'm not so sure this is the same proposal as with #146. What @jofftiquez proposes would be a simple option to just draw a line between all available data points, even if there are `null` values. No need for repetition or interpolation of available data points.

As said in @ jofftiquez post, this is the same as [Chart.js `spanGaps` option](https://www.chartjs.org/docs/latest/charts/line.html#line-styling) which I'm a bit surprised ApexCharts doesn't support yet. Not having this option makes ApexCharts unsuitable for certain data series with line charts imho.

<img width="851" alt="Screen Shot 2019-09-03 at 13 43 22" src="https://user-images.githubusercontent.com/3188392/64170737-23372480-ce51-11e9-81e5-e7912aea9bfb.png">

@junedchhipa, please let me know if I can help with a PR that resolves this issue.

**Comment by jofftiquez** [comment] 2019-09-03 12:38
@cseelus is correct. I started using chartjs again just for this feature.

**Comment by surajkumbhar1992** [comment] 2019-09-20 15:20
do you have any resolution on this as i would like to use this chart instead of CHARTJS.
Please tell me whether it is possible or not to connect null points?

**Comment by spmsh** [comment] 2020-03-16 10:50
+1 for this feature, that would be a great and useful addition. Thanks and keep the good work.

**Comment by Heartz66** [comment] 2020-07-08 13:49
+1 this would be an amazing feature for Apexcharts

**Comment by cseelus** [comment] 2020-07-19 19:12
![0EFAA2EC-85BD-433E-9640-F3014EB4348F](https://user-images.githubusercontent.com/3188392/87883000-7d5abd00-ca04-11ea-829d-5fd9b0d8561f.jpeg)

Yeah 🎉

**Comment by junedchhipa** [comment] 2020-07-19 19:15
@cseelus If you want to submit a PR, I am happy to accept it.
Sorry for the delay, this went unnoticed for too long.

**Closed** 2021-11-12 14:26 UTC
Labels: feature-request, high-priority, no-issue-activity

**Comment by versak** [comment] 2024-07-31 14:40
Has this ever been resolved? I'm not finding anything in the docs about how to connect null data, and interpolating data won't work for my situation. Ideally, though probably more difficult, I'd like to have the lines between null data dashed or dotted or a different color to indicate missing values. 
We're using multiple charts to see trends and having the "fake" data in place of missing values would be misleading. I'd love to have a "spanGaps" option...

**Comment by JustDoItSascha** [comment] 2024-08-12 13:49
Any updates on this? It got closed, but the feature seems to not be there

**Comment by martian111** [comment] 2024-08-19 13:06
This did not appear to working as of 3.46.0.  It did when I was testing 3.44.0 through 3.45.1, but that was buggy when zoomed into (for example:  https://codepen.io/martian111/pen/poXWmBg).  But starting with v3.46.0, it no longer connected the points with null values in between (see: https://codepen.io/martian111/pen/qBzVZwV).

For me, the best comparable solution I've found was plotly.js (in combination with react-plotly.js) to get this working out-of-the-box.  The configuration for it is actually intuitive, as each line on the chart cn be configured with a `connectgaps` setting as one would expect.  Example:  https://codepen.io/martian111/pen/RwzjVGL
