### ISSUE TITLE
Performance and markers.

### ISSUE THREAD

**Issue by maasha** [apexcharts/apexcharts.js#928] opened 2019-09-20 07:39 UTC
I want to plot two data series: one with 10 data points with markers and one with +5000 data points and no markers. Using:

```
markers: {
   size: [5, 0],
}
```

the rendering is dead slow?

**Comment by m50434** [comment] 2019-09-21 16:24
did you turned on datalabels? This made my datasets (with just 500 entries) quite slow !!!
Wihtout datalabels its fast (anyway I dont know why it takes so much time to print the datalabels).

**Comment by maasha** [comment] 2019-09-22 06:10
Data labels and animations are turned off.

**Comment by junedchhipa** [comment] 2020-01-20 17:36
I cannot reproduce this anymore.
Markers with size 0 are not rendered now.

Closing this.
Please let me know if the problem still persists.

**Closed by junedchhipa** 2020-01-20 17:36 UTC
