### ISSUE TITLE
When updating the options, the zoom reset does not rescale to the right min/max

### ISSUE THREAD

**Issue by philfontaine** [apexcharts/apexcharts.js#1134] opened 2019-12-13 20:44 UTC
## Codepen

https://codepen.io/philfontaine/pen/qBEaNaQ

## Explanation

This behaviour seems broken to me, but this might just be "by design", so I will let you be the judge.

I'm creating a chart, which has an initial and irrelevant min and max, let's say 0 and 10. When my AJAX call completes, I now have the data, and I update the options based on the min/max of my data, let's say 0 and 100, and I update the series as well, which all works just fine. Then, I zoom into the data, the yaxis is still from 0 to 100. Then, I click the Reset button, and the yaxis returns to 0 to 10, which makes absolutely no sense. Then, when I zoom again, I return to the 0 to 100 scale. (You can see this behavior in the codepen)

Now, is this a bug, or is this normal? Should my workaround be to destroy the chart and create a new one? I have no problem if this is the case, it's just that I spent a few hours trying to debug that problem, and I just wanted to make sure that this was intended behavior.

**Comment by junedchhipa** [comment] 2019-12-26 18:53
You are absolutely correct. I have fixed it in the last commit.
When the new version is released, please report whether the issue is fixed on your side.

**Closed** 2019-12-26 18:52 UTC
Labels: bug
