### ISSUE TITLE
Bar Chart : Labels are displayed with decimal values when the highest series data is less than 5

### ISSUE THREAD

**Issue by shanprsd** [apexcharts/apexcharts.js#798] opened 2019-07-25 08:05 UTC
![image](https://user-images.githubusercontent.com/30957711/61855220-4d560800-aedd-11e9-9106-492459635389.png)

I am using Apex Chart's **Distributed Column Chart**

This is the data value I provided in series:

`series: [{
      data: [4, 1]
    }],`

From this data, I am expecting the labels on Y-axis to be rendered as  `0, 1, 2, 3, 4` but that doesn't seem to happen. I tried putting the highest value to `5` in the data array and it rendered correctly. 

So the problem here is that I am not able to handle the case when highest value is less than 5 as in the series above for `[4, 1]`.

I tried `formatter` callback for labels where I used `Math.floor()` but that didn't work either as it displayed `0, 0, 1, 2, 3, 4`

Thanks

**Comment by ludo237** [comment] 2019-07-25 15:35
I stumble upon the same issue

**Comment by junedchhipa** [comment] 2020-01-20 17:50
```javascript
yaxis: {
  labels: {
    formatter: function(val) {
      return Math.floor(val)
    }
  }
}
```
works fine.

Closing as duplicate of #779

**Closed by junedchhipa** 2020-01-20 17:50 UTC
Labels: yaxis

**Comment by Madushankumarasiri** [comment] 2022-09-23 08:01
@junedchhipa is there any way to remove these decimal points in y axis as well? I tried 
      formatter: function(val) {
        return val.toFixed(0);
      }
    }
seems like not working.

![Screenshot 2022-09-23 132824](https://user-images.githubusercontent.com/61668132/191916236-903c3a56-0f85-4909-8577-f469a29a677e.png)
