### ISSUE TITLE
Mirrored Bar Chart not showing max positive label on x-axis

### ISSUE THREAD

**Issue by sylvermeister** [apexcharts/apexcharts.js#1001] opened 2019-10-18 06:25 UTC
## Codepen

Please check [this codepen]https://codepen.io/gesta-andrei-rakuten/pen/QWWKxwO) for the minimal demonstration. This code is also just the example posted from https://apexcharts.com/javascript-chart-demos/bar-charts/bar-with-negative-values/

## Explanation

- What is the behavior you expect?
Maximum positive x-axis is displayed
5%

- What is happening instead?
Maximum positive x-axis is not displayed

- What error message are you getting?
None

Below is attached screenshot also :)
<img width="714" alt="Screen Shot 2019-10-18 at 15 25 04" src="https://user-images.githubusercontent.com/39764096/67070619-7e339980-f1bb-11e9-9dea-73e351e6afa2.png">

**Comment by junedchhipa** [comment] 2019-10-19 14:27
This bug is already fixed 4 days ago. Will be shipped along with the next patch release.
Duplicate of #815

**Closed by junedchhipa** 2019-10-19 14:27 UTC

**Comment by sylvermeister** [comment] 2019-10-21 00:05
Nice! Thanks for your hardwork.

**Comment by sylvermeister** [comment] 2019-10-29 01:51
Hello! The issue still isn't resolved.
The max positive value for x-axis is still not showing.

**Comment by junedchhipa** [comment] 2019-10-29 02:06
The next update will be releases today.
Thanks for the patience.

**Comment by rcoundon** [comment] 2020-01-05 20:32
Hi - I'm seeing this on a regular bar chart on ApexCharts version 3.12.0 and vue-apexcharts version 1.5.1 (but mouseover works)

Should it be resolved now?
![image](https://user-images.githubusercontent.com/9136570/71785690-70432700-2ffa-11ea-9dbc-e32826335d91.png)

**Comment by marqroldan** [comment] 2020-02-10 03:36
I'm also experiencing this on 3.15.5 (apexcharts) / 1.5.2 (vue-apexcharts)
![image](https://user-images.githubusercontent.com/11716376/74119191-6b752280-4bf9-11ea-9aa4-4c1dca501fb7.png)
![image](https://user-images.githubusercontent.com/11716376/74119244-9f504800-4bf9-11ea-94a1-d322af8ce2c1.png)
