### ISSUE TITLE
SVG/PNG export is broken

### ISSUE THREAD

**Issue by Connum** [apexcharts/apexcharts.js#1424] opened 2020-03-25 10:25 UTC
# Bug report

## Codepen

No Codepen needed, it's even broken in the demos:
https://apexcharts.com/javascript-chart-demos/line-charts/basic/

Tested in Firefox, Chrome and Edge latest under Windows.

## Explanation

When opening the top right burger menu and clicking "Download SVG" or "Download PNG", nothing happens. In the console, you can see the following errors:

* SVG *
> TypeError: e.setAttribute is not a function apexcharts:6:116657
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value https://cdn.jsdelivr.net/npm/apexcharts:6
    value self-hosted:920

* PNG *
> TypeError: e.setAttribute is not a function apexcharts:6:116657

**Comment by junedchhipa** [comment] 2020-03-25 10:56
Thanks for reporting, will be fixed soon.

**Comment by junedchhipa** [comment] 2020-03-25 17:28
Closing as duplicate of #1419

**Closed by junedchhipa** 2020-03-25 17:28 UTC
