### ISSUE TITLE
Candlestick Chart can be mixed with Line chart ? 

### ISSUE THREAD

**Issue by phamthanhphuocloc1995** [apexcharts/apexcharts.js#1018] opened 2019-10-23 03:19 UTC
Can I combine Candlestick Chart  with LineChart in coordinate axis ?  I don't see anything in the document.

Like this 
![Capture](https://user-images.githubusercontent.com/45279379/67354163-95d59e00-f57e-11e9-9ea1-005feab86934.PNG)

**Comment by junedchhipa** [comment] 2019-10-23 06:03
This is not supported yet, but being considered.
Closing as duplicate of #883

**Closed by junedchhipa** 2019-10-23 06:03 UTC

**Comment by KonScanner** [comment] 2021-12-13 10:59
The tooltip freaks out when 2+ lines are added. Is there a way to create a custom function for candlestick + line graphs for the tooltip?

**Comment by csskevin** [comment] 2023-01-02 22:33
Any updates on this? Would be great to have multiple lines on a candlestick graph. Is there maybe another way doing that?
