### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by hongpatipan** [apexcharts/apexcharts.js#4620] opened 2024-08-05 05:31 UTC
I can't access your website, it says 502 Bad Gateway.

url: [https://apexcharts.com/javascript-chart-demos/](url)

![image](https://github.com/user-attachments/assets/f8984d1e-dbe4-43e3-bbc9-eee3a6bf6a97)

**Comment by junedchhipa** [comment] 2024-08-05 06:37
Duplicate of #4613

**Closed by junedchhipa** 2024-08-05 06:37 UTC
