### ISSUE TITLE
Area Graph - Fill between two lines

### ISSUE THREAD

**Issue by SwathiMystery** [apexcharts/apexcharts.js#1003] opened 2019-10-19 14:09 UTC
Thank you @junedchhipa for the beautiful charts you have built! +1

Just a query, since I could not find anything around this.
Can I fill the area between two running lines?
Like this : 
![image](https://user-images.githubusercontent.com/1615134/67146350-dd6ed800-f2a7-11e9-9ef0-d9e20b459842.png)

If yes, could you please let me know how?
Sorry if I have missed something very fundamental here.

Thanks for your help in advance!

**Comment by junedchhipa** [comment] 2019-10-19 14:12
This feature is not supported currently but has been already requested.
Duplicate of #184

**Closed by junedchhipa** 2019-10-19 14:12 UTC
