### ISSUE TITLE
Add ability to render mixed chart grid lines as per previous versions

### ISSUE THREAD

**Issue by tommitch** [apexcharts/apexcharts.js#1384] opened 2020-03-12 09:38 UTC
The mixed chart, when mixing column and lines, used to extend the grid all the way behind the columns (v3.11.3). After updating to v3.16.1 to bring in [this fix](https://github.com/apexcharts/apexcharts.js/issues/1359) the grid of chart no longer extends this far.

I can't see an option to revert the grid to the old behaviour. Is there a way to achieve this with v3.16.1?

The charts in the screenshot use the exact same options;
- 6 line series
- 1 column series
- x axis type of datetime

I'm not sure if it matters but we're rendering the charts react-apexcharts 1.3.6

Behaviour in v3.11.3
![Screenshot 2020-03-12 at 09 14 50](https://user-images.githubusercontent.com/1867626/76506936-dce80100-6443-11ea-90b1-2406bcb5e3db.png)

Behaviour in 3.16.1
![Screenshot 2020-03-12 at 09 15 09](https://user-images.githubusercontent.com/1867626/76506969-ea04f000-6443-11ea-97a2-4fc4a5a2e4fd.png)

**Comment by Carniatto** [comment] 2020-04-07 09:42
@junedchhipa Can we discuss this feature this is breaking my app very badly when you have small series

![image](https://user-images.githubusercontent.com/1366831/78654068-b5624800-78cc-11ea-8821-1db6eacb5f2d.png)

this is the link: https://codesandbox.io/s/apx-combo-line-area-column-j5e0o?file=/src/app/app.component.ts

**Comment by junedchhipa** [comment] 2020-04-07 09:49
@Carniatto I have labeled the issue a bug, so it will be addressed soon.
Meanwhile, you can disable datetime xaxis as a workaround.

**Comment by Carniatto** [comment] 2020-04-07 09:57
@junedchhipa  Thanks for the quick response 😃 

The problem seems to be bigger than that since I can reproduce even without any datetime axis

![image](https://user-images.githubusercontent.com/1366831/78655894-4803e680-78cf-11ea-8781-a1e0617df59c.png)

[Link](https://codesandbox.io/s/apx-combo-multiple-yaxis-3fgui?file=/src/app/app.component.ts)

**Comment by junedchhipa** [comment] 2020-04-07 18:25
Alright, yeah that seems like wrong padding for bar charts.
I will take a look soon.

**Comment by junedchhipa** [comment] 2021-11-07 14:05
As of v3.29.0, this problem doesn't seem to be happening.
Closing this.

**Closed by junedchhipa** 2021-11-07 14:05 UTC
Labels: bug, bar
