### ISSUE TITLE
pie-chart dataLabelsGroup is null

### ISSUE THREAD

**Issue by tabbed** [apexcharts/apexcharts.js#408] opened 2019-03-17 13:59 UTC
## Codepen

https://codepen.io/anon/pen/ywjwQj

## Explanation
There's an exception when hovering the pie chart pieces.
dataLabelsGroup is null

- What is the behavior you expect? - no expection
- What is happening instead? exception is thrown, but i didn't notice any functional problem.
- What error message are you getting?
Uncaught TypeError: Cannot read property 'style' of null
    at t.value (VM71 apexcharts:6)
value @ apexcharts:6

**Comment by junedchhipa** [comment] 2019-03-17 14:07
Fixed in https://github.com/apexcharts/apexcharts.js/commit/88e547e463a6ed9da4f56c95f2b1da567ef11ef3
Duplicate of #403

**Closed by junedchhipa** 2019-03-17 14:07 UTC
