### ISSUE TITLE
radial chart endShape: 'round'

### ISSUE THREAD

**Issue by Angular-Mast** [apexcharts/apexcharts.js#1121] opened 2019-12-09 02:40 UTC
![image](https://user-images.githubusercontent.com/54040005/70402908-c3ce4f00-1a13-11ea-8fa1-d0997ca1a63b.png)

I want to draw a radial chart like this...

In the bar chart, we have got an option for this but I can't find any for radial chart.

I tried this way:
```
stroke: {
        lineCap: 'round'
},
```

It rendered all strokes rounded and it is not fit to my case.
any idea?

**Comment by junedchhipa** [comment] 2019-12-09 07:05
Sorry, different shape for start and end paths is not supported in radial-bar charts. It will be both sides rounded or both sides flat.
Duplicate of #1076

**Closed by junedchhipa** 2019-12-09 07:05 UTC

**Comment by Angular-Mast** [comment] 2019-12-09 12:56
Hey, @junedchhipa 

Is there any solution?
