### ISSUE TITLE
Label multiline display

### ISSUE THREAD

**Issue by TYQbag** [apexcharts/apexcharts.js#1814] opened 2020-08-03 02:51 UTC
# Bug report

## Explanation

There are so many restrictions on what kind of multiline display, when My type is datetime, I can't wrap the label.please give me advise,tnanks

**Comment by erfanSW** [comment] 2020-08-03 21:00
I have the same issue

**Comment by TYQbag** [comment] 2020-08-04 01:11
I try to use two chart,It's works

**Comment by junedchhipa** [comment] 2020-08-06 18:11
Duplicate of #1811

**Closed by junedchhipa** 2020-08-06 18:11 UTC
