### ISSUE TITLE
Missing in the documentation? - rangeBar, timeline chart

### ISSUE THREAD

**Issue by rafaelturse** [apexcharts/apexcharts.js#893] opened 2019-09-05 00:44 UTC
Please, how can I add a new range to the same series on the same line? Sorry, but I didn't find it in the documentation. If not, it would be a great feature to add. Thanks.

**Comment by junedchhipa** [comment] 2019-09-05 06:32
Not implemented currently, but it is in the roadmap.

Closing as duplicate of #560

**Closed by junedchhipa** 2019-09-05 06:32 UTC
