### ISSUE TITLE
(VueApexCharts) Chart content is not properly aligned in certain cases (Firefox)

### ISSUE THREAD

**Issue by mattilind** [apexcharts/apexcharts.js#406] opened 2019-03-17 11:22 UTC
Wasn't able to demonstrate this using a Codepen.

![plot-bug](https://user-images.githubusercontent.com/48258345/54489554-27c54c00-48b6-11e9-99e0-26d26ae03095.PNG)

Out of Chrome and Firefox, only Firefox seems to have this issue. However, the charts do render correctly when:

1. Page is re-sized
2. Chart series' data is changed which causes a re-render. 

One particular thing about getting this issue was that the charts were inside a hidden element when the series' data was changed, and upon showing the element this is how they looked. Doing either of the two things described above corrected the alignment.

The charts were in a UI which was built using Vue 3.4.1 and Vuetify 1.5.5.

**Comment by mattilind** [comment] 2019-03-17 12:17
This should have been in VueApexCharts, sorry!

**Comment by junedchhipa** [comment] 2019-03-17 14:06
CLosing as the duplicate of https://github.com/apexcharts/vue-apexcharts/issues/77

**Closed by junedchhipa** 2019-03-17 14:06 UTC
