### ISSUE TITLE
Scatter and bubble charts do not adapt to their container size

### ISSUE THREAD

**Issue by Elborh** [apexcharts/apexcharts.js#788] opened 2019-07-23 21:32 UTC
## Codepen
https://codepen.io/Elborh/pen/RXabNY

## Explanation
It seems that certain chart types (at least bubble and scatter charts) do not adapt to their container new size once it gets changed.

For illustration, this [codepen](https://codepen.io/Elborh/pen/RXabNY) has two charts placed in the resizeable boxes. If I resize the bar chart box, the chart itself immediately adapts to its containier size. However, resizing the scatter chart box has no effect on the chart size.

Highly appriciate your support on this.

**Comment by junedchhipa** [comment] 2020-01-18 13:43
This seems to be fixed in the latest version 3.15.2
Closing it as cannot reproduce it.

**Closed by junedchhipa** 2020-01-18 13:43 UTC
Labels: bug
