### ISSUE TITLE
Zoom is disabled in a Vertical Bar Chart

### ISSUE THREAD

**Issue by Ahmed-Elkholy** [apexcharts/apexcharts.js#1437] opened 2020-03-26 19:00 UTC
# Bug report

## Codepen

https://codepen.io/ahmed-elkholy/pen/bGdQmYR

## Explanation

- What is the behavior you expect?
I am expecting that I should be able to zoom in vertical bar charts
- What is happening instead?
Zooming is disabled and zoom tools do not appear in toolbars.
- What error message are you getting?
N/A

**Comment by junedchhipa** [comment] 2020-03-26 19:31
Closing as duplicate of #1436

**Closed by junedchhipa** 2020-03-26 19:31 UTC
