### ISSUE TITLE
Differences between Category and Datetime in a column chart

### ISSUE THREAD

**Issue by szacchino** [apexcharts/apexcharts.js#1479] opened 2020-04-09 08:43 UTC
Hi, using apexcharts I've difficulties to implement a column chart. If I set xaxis.category as "category" the chart is rendered proportionally to given window. When I use xaxis.category as "datetime", the preferred way for me, the result is a smaller chart even without grid lines spanning for the whole width of the chart. In my humble opinion, I don't think that the difference in category setting justifies the differences in the final aspect of the chart; at least the programmer should be able to choose which version of the chart should be produced.

Please take a look at this fiddle: https://jsfiddle.net/szacchino/ds1qvmpj/
There you'll find two charts as described above.  The second one (chart2) is the result I would like to achieve.

Thank you

**Comment by junedchhipa** [comment] 2020-04-09 11:36
You're absolutely correct and this has been worked on currently.
The issue is already mentioned in https://github.com/apexcharts/apexcharts.js/issues/1384 so closing this.
Rest assured that it will be addressed soon.

**Closed by junedchhipa** 2020-04-09 11:36 UTC
