### ISSUE TITLE
Inconsistent Data Label positioning in horizontal Bar Charts

### ISSUE THREAD

**Issue by JCQuintas** [apexcharts/apexcharts.js#72] opened 2018-09-03 17:26 UTC
There are a few insconsistencies in Data Label's positions. (Was working in 1.3.18 before upgrading to 1.4.2)

As you can see in https://codesandbox.io/s/oq85k0l2wq 

Both graphs have the same absolute values, but one is negative and the other positive. Values 0.01 and 0.02 have a diferent position than -0.01 and -0.02. Also, the values with Zero position themselves weidly in boths graphs.

**Comment by junedchhipa** [comment] 2018-09-03 19:31
This might be the cause of the commit which fixed 0 value appearance on bar charts as it was not correctly being displayed before.
Thanks for reporting. I will look into it

**Comment by junedchhipa** [comment] 2018-09-06 06:30
Fixed in https://github.com/apexcharts/apexcharts.js/commit/8c456df21ae830af1febcde9612b138be971db1d

**Closed by junedchhipa** 2018-09-06 06:30 UTC
