### ISSUE TITLE
Hiding a single series causes it to disappear instead of merely hiding it

### ISSUE THREAD

**Issue by MellyCodes** [apexcharts/apexcharts.js#923] opened 2019-09-16 12:42 UTC
## Explanation

- What is the behavior you expect?

**When clicking on a single series on a chart, for it to just hide (grayed out?), as with charts with more than one series**

- What is happening instead?

**The legend completely disappears, along with the chart's data, with no way to get it back other than refreshing the page.**

- What error message are you getting?

**No error message**

- More info: 

**One suggestion would be a way to make a `toggleDataSingleSeries: false` option. My project has a lot of charts which use multiple series, so disabling the toggle would not be an option.**

![single](https://user-images.githubusercontent.com/25773903/64958642-0560bb00-d866-11e9-93a9-99deab3ea14e.PNG)
![singlegone](https://user-images.githubusercontent.com/25773903/64958643-0560bb00-d866-11e9-908d-6b0f232af098.PNG)

**Comment by MellyCodes** [comment] 2019-09-16 12:51
I just noticed that someone else submitted this issue, even after I searched before posting. Has it been resolved?

**Comment by junedchhipa** [comment] 2019-09-16 12:53
Yes, this is a duplicate of #919 
It has been fixed, but not released yet.
You can expect the next patch release in a week or two.

**Closed by junedchhipa** 2019-09-16 12:53 UTC

**Comment by MellyCodes** [comment] 2019-09-16 12:58
Perfect, thanks so much. :)
