### ISSUE TITLE
problem with rangeBar chart

### ISSUE THREAD

**Issue by itsmnj** [apexcharts/apexcharts.js#786] opened 2019-07-23 11:46 UTC
Hi Dear,
Please have a look at below image

![rangeBar chart](https://user-images.githubusercontent.com/40417305/61709243-30e48f00-ad68-11e9-8414-61b27c2e3c6a.png)

if you observe from the above image Design, Code, Test and Deployment is repeating on y-axis twice. i have scenario that y-axis data should not be repeat and should be drawn against the first existing entry.

it should look like below image

![rangeBar chart 2](https://user-images.githubusercontent.com/40417305/61709731-4b6b3800-ad69-11e9-957f-24f140bc7d43.png)

can you please confirm how i can achieve this and also how i can use rangeBar with line chart in synchronize charts.

Let me know if i can be of assistance.

thank you for you help.

Regards,

**Comment by junedchhipa** [comment] 2019-07-23 16:49
Currently, this feature is unavailable but has been requested previously. 
It is in the roadmap and will be implemented in the future.
Closing as duplicate of #560

**Closed by junedchhipa** 2019-07-23 16:49 UTC
