### ISSUE TITLE
"opts.ctx.rangeBar.getTooltipValues is not a function" when hovering over timeline bar

### ISSUE THREAD

**Issue by jayshah1232** [apexcharts/apexcharts.js#3468] opened 2022-11-02 16:28 UTC
### Description

I'm using ApexCharts to create a timeline chart that has multiple series and grouped rows. It's very similar to the example chart in the docs located here: https://apexcharts.com/javascript-chart-demos/timeline-charts/multiple-series-group-rows/

The problem I'm facing is in regards to the tooltip - hovering over any section of any bar does not display a tooltip and returns the error "opts.ctx.rangeBar.getTooltipValues is not a function" to the console. This is actually happening to me on the example page as well.

### Steps to Reproduce

1. Hover over any section of the timeline graphs in the docs. No tooltip will appear.
2. Open console to see error. 

### Expected Behavior
A tooltip should appear over the bar where the user is hovering over to display information as outlined in the tooltip options.

### Actual Behavior
Nothing appears and an error is thrown to the console. Error shown is "opts.ctx.rangeBar.getTooltipValues is not a function"

### Screenshots

![image](https://user-images.githubusercontent.com/27381013/199544031-51c40cd2-bb2e-4b35-8752-527b5e810a2b.png)
Notice the lack of tooltip appearing while I'm hovering over the bar.

### Reproduction Link

Here is the codepen link: https://codepen.io/jayshah1232/pen/wvXGJeR
It's still just the same chart as the presidents multiple series group rows example I linked earlier.

**Comment by junedchhipa** [comment] 2022-11-03 19:10
duplicate of #3453

**Closed by junedchhipa** 2022-11-03 19:10 UTC
Labels: bug, verified
